<?php header("Content-type: application/x-msdownload"); 
header("Content-Disposition: attachment; filename=customer.xls"); 
echo "No Cust	Nama Lengkap	No Member	Tgl Valid	L/P	Alamat	Kota	Email	Tgl Lahir	Status Nikah	Status	
000043	BAPAK AMIN	-	-	L	JL.PENGSONG I NO.28 BTN PENGSONG INDAH	PERAMBUAN LABU API,LOMBOK BARAT	-	0000-00-00	-	Aktif
000042	PERCETAKAN ASIH	-	-	L	JL.RE MARTADINATA 17	TUBAN	-	0000-00-00	-	Aktif
000041	PELANGI	-	-	L	JL.KH A.DAHLAN NO.3	TUBAN	-	0000-00-00	-	Aktif
000040	SULDJAYA	-	-	L	JL.SULAWESI NO.144	MAKASAR	-	0000-00-00	-	Aktif
000039	ATLANTIK	-	-	L	JL.LOMBOK NO 3	PONOROGO	-	0000-00-00	-	Aktif
000038	TOKO NUSANTARA	-	-	L	JL.PANGLIMA SUDIRMAN NO.39	TRENGGALEK	-	0000-00-00	-	Aktif
000037	TK BUKU UTAMA	-	-	L	RUKO PANGLIMA SUDIRMAN B2	JL.HASANUDIN,TULUNG AGUNG	-	0000-00-00	-	Aktif
000036	TK ASEAN	-	-	L	JL.TEUKU UMAR 61F	TULUNG AGUNG	-	0000-00-00	-	Aktif
000035	MEGARIA	-	-	L	JL.WR SUPRATMAN 82	TULUNG AGUNG	-	0000-00-00	-	Aktif
000034	GLORIA	-	-	L	JL.WR SUPRATMAN 88	TULUNG AGUNG	-	0000-00-00	-	Aktif
000033	LARIS	-	-	L	JL.PUCANG ANOM 12A	SURABAYA	-	0000-00-00	-	Aktif
000032	TOKO REMAJA	-	-	L	JL.PAHLAWAN 21	PARE	-	0000-00-00	-	Aktif
000031	TOKO SURYA	-	-	L	JL.R.A BASUNI NO.142	MOJOKERTO	-	0000-00-00	-	Aktif
000030	ABADI	-	-	L	JL.RAYA GROGOL NO.31	SOLO BARU	-	0000-00-00	-	Aktif
000029	TK KALIANYAR	-	-	L	JL.MASTRIP 81	LAMONGAN	-	0000-00-00	-	Aktif
000028	CHANDRA ST	-	-	L	JL.GATOT SUBROTO VIII/6	(BELAKANG ADIRA) PROBOLINGGO	-	0000-00-00	-	Aktif
000027	TK JULI JAYA	-	-	L	JL.TRUNOJOYO 75	PAMEKASAN	-	0000-00-00	-	Aktif
000026	TK KARISMA ST	-	-	L	JL W.J.LALAMETIK NO.76 EOBOBO	KUPANG,NTT	-	0000-00-00	-	Aktif
000025	BEST ST(BUDI)	-	-	L	KALI RUNGKUT 27,RUKORUNGKUT C-78	SURABAYA	-	0000-00-00	-	Aktif
000024	TK SIMPANG DAMAI	-	-	L	JL.TADOLAKU NO.3	PALU	-	0000-00-00	-	Aktif
000023	RAPI INDAH	-	-	L	JL.WAHIDIN 81	LAMONGAN	-	0000-00-00	-	Aktif
000022	TK MATAHARI	-	-	L	JL.WUNI NO.24	MADIUN	-	0000-00-00	-	Aktif
000021	SUMBER JAYA	-	-	L	JL.P B SUDIRMAN NO.98	PARE	-	0000-00-00	-	Aktif
000020	TK SINAR MAKMUR	-	-	L	JL.TEUKU UMAR NO.31-32	BONDOWOSO	-	0000-00-00	-	Aktif
000019	ANEKA PLAKBAN	-	-	L	JL.SUNGAI POSO NO.70	MAKASAR	-	0000-00-00	-	Aktif
000018	MHS (KEDIRI)	-	-	L	AGUS SALIM NO.114, BANDAR	KIDUR MOJOKERTO	-	0000-00-00	-	Aktif
000017	TK ERA	-	-	L	JENDRAL SUDIRMAN BP BLOK A1 NO.20,B/PAN	-	-	0000-00-00	-	Aktif
000016	MASTER	-	-	L	CANDRA KIRANANO.6 BANJARMANTRI	CAKRA LOMBOK	-	0000-00-00	-	Aktif
000015	IRA	-	-	L	JL. ARGO PURO 20	SURABAYA	-	0000-00-00	-	Aktif
000014	BERDIKARI (MKSR)	-	-	L	G LATIMOJONG,KOMP PELITA/MARGA MAS C6-C7	MAKASAR	-	0000-00-00	-	Aktif
000013	ALPHA PROMOSI	-	-	L	JL	SURABAYA	-	0000-00-00	-	Aktif
000012	ABADI AGUNG	-	-	L	JL.PERINTIS KEMERDEKAAN K/M9 NO.9	MAKASAR	-	0000-00-00	-	Aktif
000011	DIPA JAYA	-	-	L	JL.KABAENA NO.17	MAKASAR	-	0000-00-00	-	Aktif
000010	SUMBER HIDUP/JIMMY	-	-	L	JL.LABU NO. 40	MAKASSAR	-	0000-00-00	-	Aktif
000009	AUK(SUBUR MAKMUR)	-	-	L	DARMO HILL BLOK O NO.38	SURABAYA	-	0000-00-00	-	Aktif
000008	SUMBER KASIH	-	-	L	JL.COKROAMINOTO NO.47	PALU/0451421538	-	0000-00-00	-	Aktif
000007	CENTRAL JAYA	-	-	L	JL.KUNDURI NO.5	PALU/0451460935	-	0000-00-00	-	Aktif
000006	BEN(PALU)	-	-	L	JL.ASEM III/89	PALU	-	0000-00-00	-	Aktif
000005	MANTAP(MTP/NTL/PALU)	-	-	L	HOS COKROAMINOTO NO.27	PALU	-	0000-00-00	-	Aktif
000004	AUTO PRINT	-	-	L	G LATIMOJONG,RUKO LATIMOJONG 46/B6-B8	MAKASAR	-	0000-00-00	-	Aktif
000003	ABDI AGUNG	-	-	L	JL.PERINTIS KEMERDEKAAN KM 9 NO.9	MAKASAR	-	0000-00-00	-	Aktif
000002	PUTRA JAYA MANDIRI(PJM)	-	-	L	JL.DIPONEGORO NO.71	MAKASAR	-	0000-00-00	-	Aktif
000001	CAHAYA ABADI/ 081331330158	-	-	L	LEBAK ARUM GANG VNO.52	SURABAYA	-	0000-00-00	-	Aktif
ON001	ONE ASIA STATIONARY	-	-	-	RK CENTRAL GREENVILLE JL.	MANGGA 1 NO.2H	-	-	-	Aktif
JA016	JAMES	-	-	-	JL	JKT(98109159)	-	-	-	Aktif
HI003	HIDAYAH	-	-	-	JL.PANGESANGAN NO.2F	SURABAYA	-	-	-	Aktif
WI012	WIJAYA	-	-	-	JL.PANGLIMA SUDIRMAN 33	BLITAR	-	-	-	Aktif
MU019	MULIA JAYA	-	-	-	KREMBANGAN BARAT 27	SURABAYA	-	-	-	Aktif
74001	74 STATIONARY	-	-	-	JL.KERTAREJASA 17	MALANG(453838)	-	-	-	Aktif
SU060	SUPARMO(COCK)	-	-	-	JL	NGANJUK	-	-	-	Aktif
PA020	PAK MAR	-	-	-	PETEMON BARAT 33	SBY(77557050)	-	-	-	Aktif
MA033	MACK ST	-	-	-	JL	JKT(6916767)	-	-	-	Aktif
PU019	PURNAMA ST	-	-	-	JL.DUKUH KUPANG BARAT XVI	/8,SURABAYA	-	-	-	Aktif
SO004	SONI	-	-	-	JL.MURADIRAYA NO.4	SEMARANG	-	-	-	Aktif
NA007	NATALIA STAR	-	-	-	JL.PERAK TIMUR 44	SBY(3570972)	-	-	-	Aktif
SU059	SUMBER ILMU(BU MAJI)	-	-	-	JL.MANUKAN TAMA E/3	SURABAYA	-	-	-	Aktif
DE002	DEMPO INTI SARANA	-	-	-	KAPUK RAYA 21,KOMPL NUSA	INDAH 168,JKT	-	-	-	Aktif
SA033	SANGGAR KERTAS	-	-	-	JL. MANYAR TIRTOYOSO 46	SBY	-	-	-	Aktif
NY003	NYOMAN KERTAS	-	-	-	PLOSOK TIMUR VII NO 62	SBY	-	-	-	Aktif
JA015	JAYA ABADI	-	-	-	SONGOYUDAN 11	SBY(3524559)	-	-	-	Aktif
S 002	S L	-	-	L	JL.AMARTA RAYA NO.9,NGABE	YAN KARTOSURO	-	0000-00-00	-	Aktif
BU014	BU NUR	-	-	-	JL.JAGIR WONOKROMO	SURABAYA	-	-	-	Aktif
JA014	JAP	-	-	-	JL	SURABAYA	-	-	-	Aktif
NA003	NAPINDO	-	-	-	BANDENGAN UTR 14 FG,	JAKARTA	-	-	-	Aktif
EM002	EMICO	-	-	-	KOMP. D.H.I BLOK.OO/44 KA	PUK MUARA,JKT U	-	-	-	Aktif
WI007	WINSON CEMERLANG	-	-	-	JELAMBAR UTAMA 3/NO.31	JAKARTA	-	-	-	Aktif
SI013	SINAR SURYA SUPPLIER	-	-	-	SUNTER KARYA SLT H2/1-2	JAK-UT	-	-	-	Aktif
EX004	EXP.BATA JASA SAMPURNA	-	-	-	KOMP DHI BLOK KK/58	JKT(JRSN MDN)	-	-	-	Aktif
SA032	SAUDARA JAYA (ASEN)	-	-	-	JL.BANDUNG NO.110	MEDAN	-	-	-	Aktif
SI053	SINAR KOTA  (CHANDRA)	-	-	-	JL.PALANGKARAYA NO.15/128	MEDAN	-	-	-	Aktif
SI052	SINAR KOTA	-	-	-	JLN.PALANGKARAYA NO.15 /	128, MEDAN	-	-	-	Aktif
CV008	CV.BUANA MAS	-	-	-	JL.MARGOMULYO 44 HH/15	ASEM ROWO,SBY	-	-	-	Aktif
SI051	SISWA (2)	-	-	-	JL.AGUS SALIM NO.45	MADIUN	-	-	-	Aktif
SU058	SURYA MANDIRI (IHSAN M)	-	-	L	JL.TRANS KALIMANTAN.KOMPL DALAM SAKTI K/25	RT 23 HANDIL BAKTI,BANJARMASIN	-	0000-00-00	-	Aktif
UD021	UD JAVA LESTARI(WANDI)	-	-	-	SURYANATA A/5,BENOWO	SBY	-	-	-	Aktif
YU004	YUNITA	-	-	-	JL.ISTANA DIENG TENGAH 3	NO.3 MLG	-	-	-	Aktif
MA032	MARIO	-	-	-	JL	SBY	-	-	-	Aktif
PA019	PAK ZAKY (ZK)	-	-	-	JL.DIRGANTARA III B6/17	MALANG	-	-	-	Aktif
SA031	SANTOSO	-	-	-	PERUM PONDOK GEDE D/1	JEMBER	-	-	-	Aktif
PE012	PERCETAKAN 106	-	-	-	JL. RAYA TROPODO NO.106	SIDOARJO	-	-	-	Aktif
KO013	KOPRASI TJIWI KIMIA	-	-	-	JL.	MOJOKERTO	-	-	-	Aktif
PA018	PAPERINDO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
MU018	MUNG-MUNG/LISA	-	-	-	JL	JAKARTA	-	-	-	Aktif
ME023	MESTIKA DHARMA	-	-	-	JL.THAMBRIN BARU NO.36	MEDAN	-	-	-	Aktif
SI050	SINAR ABADI(A FUNG)	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SA030	SAUDARA JAYA (ACHONG)	-	-	-	JL.PALANGKA RAYA 28/49	MEDAN	-	-	-	Aktif
SI049	SINAR ABADI	-	-	-	JL.BELIMBING MANIS 54	PANGKALANBUN	-	-	-	Aktif
TK026	TK SUNNY BOY(SPS)	-	-	-	JL.SIMPANG TENAGA II/8	BLIMBING,MLG	-	-	-	Aktif
PR005	PRIMA JAYA/EEN	-	-	-	JL.TEMBUS TERMINAL KM.6	RT 20,B/SIN	-	-	-	Aktif
SI048	SI-7	-	-	-	PROYEK PASAR PAGI LAMA	SI-7,JAK BAR	-	-	-	Aktif
JL001	JM SMG/ PPD	-	-	-	JL.INDUSTI 14 NO:501-503	SEMARANG	-	-	-	Aktif
KO012	KOH ACIN	-	-	-	JL	SURABAYA	-	-	-	Aktif
CO004	COUNTER CHINA	-	-	-	-	-	-	-	-	Aktif
BE009	BERSINAR	-	-	-	KOMP PURI KALIJUDAN KAV.	C30 NO.20,SBY	-	-	-	Aktif
UT006	UTAMA	-	-	-	JL. KORBAN 40.000 NO 98	MAKASAR	-	-	-	Aktif
KO011	KOH WAWA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SE037	SETUJU JAYA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
HA019	HALMART	-	-	-	JL.GATOT SUBROTO NO.88	PROBOLINGGO	-	-	-	Aktif
SU057	SUBUR MURNI	-	-	-	-	SURABAYA	-	-	-	Aktif
BE008	BEUTY	-	-	-	JL.BRAWIJAYA 134 MUNCAR	BANYUWANGI	-	-	-	Aktif
AH004	AHOO	-	-	-	JL	SBY	-	-	-	Aktif
CA015	CAHAYA HARAPAN / FREDY	-	-	-	JL.VETERAN NO.1 RT 27	BANJARMASIN	-	-	-	Aktif
ME022	MEGAN	-	-	-	RUKAN BANDENGAN INDAH D/3	JAK-UT	-	-	-	Aktif
TK025	TK.SURYA LESTARI	-	-	-	JLN.SULTAN AGUNG NO.21	JAMBI	-	-	-	Aktif
KR001	KRISNA(MEJA BELAJAR)	-	-	-	-	-	-	-	-	Aktif
RU003	RUDY MUIS	-	-	-	JKT	-	-	-	-	Aktif
SU056	SUMBER BERKAT	-	-	-	JL.MERDEKA NO.46	MOJOWARNO	-	-	-	Aktif
SU055	SURYA TERANG	-	-	-	JL	SURABAYA	-	-	-	Aktif
TE013	TEDDY	-	-	-	PLOSO TIMUR II/8	SURABAYA	-	-	-	Aktif
MU017	MULTI BERKAT KREASI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
YA003	YASA PLASTIK	-	-	-	JL.GAJAH MADA NO.106	TUBAN	-	-	-	Aktif
AN029	ANDY STATIONARY	-	-	-	PIK,KOMPLEK ELANG LAUT	TH III/F NO.17	-	-	-	Aktif
UD020	UD MANTAP	-	-	-	I GUSTI KETUT JELANTIK GO	SA NO.7,LOMBOK	-	-	-	Aktif
CH003	CHINDY	-	-	-	JL	-	-	-	-	Aktif
BU017	BU NUR/PAK UPIK	-	-	-	JL.	SBY	-	-	-	Aktif
BA018	BAROKAH JAYA	-	-	-	JL.SURYA NATA 93 RT 31	SAMARINDA	-	-	-	Aktif
SI047	SINAR REZEKI	-	-	-	JL.SONGOYUDAN GG.4 NO.21	SURABAYA	-	-	-	Aktif
TO042	TOKO PRAYOGI	-	-	-	JL.DR WAHIDIN HUSODO 31	LAMONGAN	-	-	-	Aktif
PT019	PT.GLOBE SURYA UDARA	-	-	-	JL.RAYA KALIABANG TENGAH	NO.50.BEKASI UT	-	-	-	Aktif
TK024	TK.SAHABAT	-	-	-	JL.BENDUNGAN SUTAMI	NO.15 I,MALANG	-	-	-	Aktif
AR007	ARLAN MOTOR	-	-	-	KUPANG	NTT	-	-	-	Aktif
MA031	MASSA MAKMOR CORPS	-	-	-	JL	-	-	-	-	Aktif
UD019	UD.GLOBAL JAYA	-	-	L	JL.PIRAN H2 NO.55	DPS-BALI	-	0000-00-00	-	Aktif
UD018	UD KAMPUS (YOGYA)	-	-	-	GORONGAN/88,BRT KMPS UPN	VTRN R-ROAD UTR	-	-	-	Aktif
AR006	ARTATEX	-	-	-	JL.WAHID HASYIM NO.178	JOMBANG	-	-	-	Aktif
HE014	HENGKI	-	-	-	JL.KAUMAN RAYA NO.15-17	MAJAPAHIT,SMG	-	-	-	Aktif
WA011	WAHYU PUTRA (WAHYU AJI)	-	-	-	JL.GUNUNG TALANG NO.6	SAMPANGAN,SMG	-	-	-	Aktif
PA017	PANCARONA	-	-	-	JL.PEJANGGIH 43,CAKRA	NRGARA,LOMBOK	-	-	-	Aktif
TA008	TAMAN PUSTAKA	-	-	-	JL.YOS SUDARSO NO.11	TUBAN	-	-	-	Aktif
SI046	SINYO	-	-	-	JL.DUKUH KUPANG 11 NO.26	SURABAYA	-	-	-	Aktif
GR007	GRIYA BUKU	-	-	-	JL.AHMAD YANI NO.39	PARE	-	-	-	Aktif
HA018	HAN JAYA	-	-	-	PATIMURA NO 4	BESUKI	-	-	-	Aktif
NA019	NATALIA	-	-	-	JLPATTIMURA 32	BESUKI	-	-	-	Aktif
GU011	GUSTI	-	-	-	JL.SELAPARANG GANG DUKU	NO.5,LOMBOK	-	-	-	Aktif
LI015	LIMA JAYA TEH(LJTEH)	-	-	-	JL.SELAPARANG NO.8 CAKRA-	NEGARA,LOMBOK	-	-	-	Aktif
JA013	JAYA MAKMUR	-	-	-	JL.KREMBUNG BARAT RT 22	RW 09,SDA	-	-	-	Aktif
FI003	FIRMAN ICHSAN	-	-	-	JL.SAM RATULANGI NO.35	MAKASAR	-	-	-	Aktif
NA018	NATALIN/KEMBANG JEPUN	-	-	-	JL.KEMBANG JEPUN 159	SURABAYA	-	-	-	Aktif
BI023	BINTANG ANUGRAH	-	-	-	JL.PERUM GUNUNGSARI INDAH	BLOK O/9,SBY	-	-	-	Aktif
DO003	DONI	-	-	-	JL	SURABAYA	-	-	-	Aktif
PD001	PD.AGS ST	-	-	-	JL	JKT	-	-	-	Aktif
BU016	BUDI PLASTIK	-	-	-	JL.PERNIAGAAN NO.10	SAMARINDA	-	-	-	Aktif
AD006	ADI NOTA	-	-	-	-	-	-	-	-	Aktif
CE003	CENTRAL ST	-	-	-	JL.AHMAD YANI 74	SINGARAJA-BALI	-	-	-	Aktif
YO008	YOYOK (YS)	-	-	-	JL. DUKUH SETRO 12/57	SURABAYA	-	-	-	Aktif
BI022	BINTANG BARU	-	-	-	JL.POGOT NO:40	SURABAYA	-	-	-	Aktif
HU002	HUSEN	-	-	-	JL.RAMBI PUJI	JEMBER	-	-	-	Aktif
GR006	GRAFIS JAYA	-	-	-	JL KEBRAON V NO.7	SURABAYA	-	-	-	Aktif
YO007	YOSSE CARD	-	-	-	JL	SEMARANG	-	-	-	Aktif
MI019	MITRA JAYA	-	-	-	JL.DUKUH SETRO 697/1A	SURABAYA	-	-	-	Aktif
AC004	ACAI	-	-	-	-	JAKARTA	-	-	-	Aktif
IS003	ISTANA SISWA	-	-	L	JL.WIHORO SAMPANGAN RT 2	YOGYAKARTA	-	0000-00-00	-	Aktif
NU004	NUGROHO STATIONARY	-	-	L	JL.TATA BUMI NO:29	YOGYA	-	0000-00-00	-	Aktif
TK023	TK.DEVI	-	-	L	JL.RENGROAD 340A	DONGKELAN,YOGYA	-	0000-00-00	-	Aktif
TK022	TK.GLORY	-	-	-	JL.GANG PINGGIR NO:9A	SEMARANG	-	-	-	Aktif
BA017	BANYU MILI (SEMARANG)	-	-	L	JL,CANDI TMBG UTR DLM 869	PASA DENA,SMG	-	0000-00-00	-	Aktif
FA011	FANNY STATIONARY	-	-	-	JL.KENDALSARI SLT NO:22	SURABAYA	-	-	-	Aktif
WI011	WINMAX	-	-	-	JL. JEMBATAN BESI 2/21	TAMBORA,JAKBAR	-	-	-	Aktif
PE011	PELE /JAKARTA	-	-	-	-	JAKARTA	-	-	-	Aktif
TO041	TOKO NIKIMURA	-	-	-	JL.KUSUMA BANGSA NO:1	PASURUAN	-	-	-	Aktif
AN028	ANTON (JKT)	-	-	-	KOMP.DHI BLOK UU NO:36	JAKARTA UTARA	-	-	-	Aktif
JO004	JONNY	-	-	-	JL.ABDUL RAHMAN 119	SURABAYA	-	-	-	Aktif
EA001	EAGLE PIANIKA	-	-	-	JL	SURABAYA	-	-	-	Aktif
BI021	BINTANG JAYA ABADI	-	-	-	JL.DEWI SARTIKA 31A	PALU	-	-	-	Aktif
SU054	SUKSES STATIONARY	-	-	-	-	JAKARTA	-	-	-	Aktif
TO040	TOKO KAPIT	-	-	-	JL.JAYAKARTA 1 NO:11	DENPASAR-BALI	-	-	-	Aktif
UD017	UD SRIDHANA	-	-	-	JL.PUKAD PANCORAN 9X	PANJER-DPS	-	-	-	Aktif
MI018	MITRA SUKSES	-	-	-	PERUM CENGKARENG INDAH	BLK HD/5 JKT	-	-	-	Aktif
RE010	RESMI ABADI LANCAR	-	-	-	JL.COKROMINOTO GANG KATA-	LIA II/2,BALI	-	-	-	Aktif
TO039	TOKO ABADI (2)	-	-	-	JL.BUSUKAN 22 RT 2 RW 27	MOJOSONGO-SOLO	-	-	-	Aktif
TO038	TOKO AMIN	-	-	-	JL.RAYA SETYABUDI 24	SRAGEN	-	-	-	Aktif
MB002	MBAK UMI	-	-	-	JL.PASAR INDUK	CEPU	-	-	-	Aktif
CI015	CIA WU	-	-	-	JL.MARGOMULYO 44 BLOK	00-38,SBY	-	-	-	Aktif
MU016	MUCHSIN	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SU053	SURYA PRATAMA	-	-	-	JL.KEDUNG COWEK 173	SBY	-	-	-	Aktif
US006	USAHA TANI	-	-	-	JL.TRUNOJOYO 56	MADIUN	-	-	-	Aktif
TK021	TK LUSI	-	-	-	SIDOTOPO WETAN BARU NO.6	SURABAYA	-	-	-	Aktif
MJ001	MJ STATIONARY	-	-	L	SUMBER NAYU RT 08/12	KADIPIRO-SOLO	-	0000-00-00	-	Aktif
CE002	CENTRAL GEMILANG	-	-	-	JL.YOS SUDARSO 78,NONO-	NGAN,SOLO	-	-	-	Aktif
TO037	TOKO ABADI (1)	-	-	-	PERUM GEDANGAN PERMAI SEK	TOR 9 K/29,SOLO	-	-	-	Aktif
PR004	PRIMA PUTRA	-	-	-	JL.DIPONEGORO NO.56	JEMBER	-	-	-	Aktif
SE036	SENYUM MEDIA	-	-	-	JL.KALIMANTAN NO.7	JEMBER	-	-	-	Aktif
SU052	SUMBER BERKAH	-	-	-	JL.MALAKA 2 NO.80	JAKARTA	-	-	-	Aktif
RO006	ROBERT	-	-	-	JL.IKAN BUNTEK 22	SURABAYA	-	-	-	Aktif
TR013	TRININDA	-	-	-	JL.INDUSTRI XX/786-787	LIK,SEMARANG	-	-	-	Aktif
BU015	BUDI	-	-	-	JL.PETERONGAN	SUKODONO	-	-	-	Aktif
TO036	TOKO PRIMA	-	-	-	BRATANG GEDE NO.52	SBY(5010647)	-	-	-	Aktif
EM003	EMBUN PAGI	-	-	-	JL.TELEPHONE KOTA NO:1	JAKARTA	-	-	-	Aktif
ME021	MEGA MANDIRI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
PT018	PT.MENTARI CAHAYA ABADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TE012	TEKA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
NA017	NADHI MAHENDRA DATA	-	-	L	JL.MAHENDRA DATA NO.100	DPS-BALI	-	0000-00-00	-	Aktif
MA030	MANDIRI BERSAMA	-	-	-	JL	JAKARTA	-	-	-	Aktif
AN027	ANTON /M-TO	-	-	-	-	MOJOKERTO	-	-	-	Aktif
JA012	JAGIR	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PU018	PUSTAKA JAYA	-	-	-	TAMAN SEMANAN INDAH BLOK	B/15,JAK-BAR	-	-	-	Aktif
LO003	LONGDA	-	-	-	JL.	-	-	-	-	Aktif
WA010	WATER FRONT	-	-	-	JL	JAKARTA	-	-	-	Aktif
TO035	TOKO ABADI	-	-	-	JL.KYAI MOJO NO.19	KEDIRI	-	-	-	Aktif
CI014	CIPTA MANDIRI	-	-	-	JL.MANGGALA MULYA 44,REJO	MULYO.MADIUN	-	-	-	Aktif
LJ001	LJS(LIMA JAYA SENTOSA)	-	-	-	JL.TEGUH FAISAL NO.10	SWETA,LOMBOK	-	-	-	Aktif
DJ002	DJM	-	-	-	JL	SBY	-	-	-	Aktif
KO010	KO AGIN	-	-	-	JL.TMN PALEM LESTARI RK-	PELANGI F/6-7	-	-	-	Aktif
MA029	MANGGALA SAKTI / BU SIANA	-	-	L	KENDALPAYAK RT 13 RW.07	PAKISAJI-MLG	-	0000-00-00	-	Aktif
SE024	SETIA	-	-	-	JL.LAWU NO.3	PARE-KEDIRI	-	-	-	Aktif
PA016	PAK SUGENG	-	-	-	JL.SIMO MARGOREJO TENGAH	GG I/18,SBY	-	-	-	Aktif
SI045	SIDOYOSO	-	-	-	-	-	-	-	-	Aktif
TO034	TOKO PRIMA	-	-	-	JL.GATOT SUBROTO NO.72	JEMBER	-	-	-	Aktif
TK020	TK.ANEKA PALEN(BOGOR)	-	-	-	JL.YOS SUDARSO NO.43	SAMARINDA	-	-	-	Aktif
AL006	ALAM SUBUR	-	-	-	KEMBANG JEPUN 144	SBY	-	-	-	Aktif
CV007	CV.SINAR SUKSES	-	-	-	JL.A.YANI KM 6,2 NO.559	BANJARMASIN	-	-	-	Aktif
AK003	AKENG	-	-	-	RAYA PRANCIS BLOK FS17/20	DADAP,TANGERANG	-	-	-	Aktif
MA028	MASTER	-	-	-	JL.JAGIRAN 36H	SURABAYA	-	-	-	Aktif
PT017	PT BINTANG CIPTA REZEKI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TO033	TOKO 107	-	-	-	JL.MT HARIONO RUKO ISTANA	DINOYO A /8,MLG	-	-	-	Aktif
EN007	ENGGAL MUKTI(MEGAH MULIA)	-	-	-	JL.DIPONEGORO 102	KARANGPLOSO	-	-	-	Aktif
CV006	CV.YUSHINCA	-	-	-	JL.TERUSAN BANDENGAN UT	JKT	-	-	-	Aktif
US005	USMAN	-	-	-	JL.	SBY	-	-	-	Aktif
TK019	TK PUTRA MERDEKA	-	-	L	JL.YOS SUDARSO NO.5	SOLO	-	0000-00-00	-	Aktif
CI013	CITIZEN RAJAWALI	-	-	-	SURABAYA	-	-	-	-	Aktif
TK018	TK KITA	-	-	L	JL.TAMBAK MAS V NO.83	SEMARANG	-	0000-00-00	-	Aktif
GO001	GOZA RETAIL & GROCERY ST	-	-	-	JL. WASPADA 40	SURABAYA	-	-	-	Aktif
FO004	FORTUNE (DESI)	-	-	-	PGRN TUBAGUS ANGKE 190RR	JEMBT 2/JAK-BAR	-	-	-	Aktif
JA011	JAYA MAKMUR(TOPLA)	-	-	-	RUKO PALEM BLOK G NO.29,	CENGKARENG,JKT	-	-	-	Aktif
TO032	TOKO ABC	-	-	-	JL.DR.SUTOMO NO.52	PROBOLINGGO	-	-	-	Aktif
TK017	TK MELATI ABADI (S-133)	-	-	-	JL.PANGERAN SURIANSYAH 24	SAMARINDA	-	-	-	Aktif
BO006	BOEN JAYA	-	-	-	JL.PANDEGILING 296	SURABAYA	-	-	-	Aktif
PU017	PUTRA PURNAMA PERKASA	-	-	-	KENDANGSARI YKP BLOK B-16	SURABAYA	-	-	-	Aktif
TO031	TOKO.MARGOMULYO (MARJOKO)	-	-	-	JL.NGADISIMO UTARA II/15	KEDIRI	-	-	-	Aktif
CA014	CAC	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PU016	PUTRA MANDIRI	-	-	-	JL.KALIJUDAN INDAH BLOK D	NO.2,SBY	-	-	-	Aktif
FE005	FERI AKO	-	-	-	SUTOREJO PRIMA SLT XI/PH-	32,SURABAYA	-	-	-	Aktif
CH002	CHANDRA STATIONARY	-	-	-	JL.BUNGURAN 23-25 F	SURABAYA	-	-	-	Aktif
TO030	TOKO AMAN MAKMUR	-	-	-	JL.PACAR KELING V NO.7	SURABAYA	-	-	-	Aktif
PT016	PT.HASIL KERTASINDO	-	-	-	JL.MUARA BARU NO.13,KOMP	GDG.CAKRA-JKT	-	-	-	Aktif
TK016	TK AL-ULYA	-	-	-	JL.CITRA NIAGA B-18(PS PA	GI)JOMBANG	-	-	-	Aktif
BI020	BIMA SAKTI	-	-	-	JL.PANDAN SARI 170	BALIKPAPAN	-	-	-	Aktif
TK015	TK AIRINE(MUJI/RIRIN)	-	-	-	KLAMPISAN RT 3/3,WIROBI-	TING PRAMBON,SD	-	-	-	Aktif
DU005	DUA DOLLAR MAS	-	-	-	JL.HASANUDIN HM NO.34	BANJARMASIN	-	-	-	Aktif
TO029	TOKO IDA	-	-	-	JL.WONOREJO II/15	SURABAYA	-	-	-	Aktif
UN005	UNTUNG MULYO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TO028	TOKO HEBAT	-	-	-	JL.DIPONEGORO NO.58	PONOROGO	-	-	-	Aktif
PA015	PAULINA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
WI006	WIJAYA SEJAHTERA	-	-	-	JL.PETEMON TIMUR NO.10	SURABAYA	-	-	-	Aktif
SU047	SURABAYA FOTO	-	-	-	JL.ADITYAWARMAN NO.74	SURABAYA	-	-	-	Aktif
TO027	TOKO UTAMA	-	-	-	JL.PANGLIMA SUDIRMAN NO.9	PASURUAN	-	-	-	Aktif
ME020	MEGA MANDIRI	-	-	-	JL.SETYOBUDI KOMP.RUKO	BLOK C/10,KRIAN	-	-	-	Aktif
GL005	GLORIA	-	-	-	JL.ANGGREK NO 22	BLITAR	-	-	-	Aktif
MB001	MBAK YULI	-	-	-	-	-	-	-	-	Aktif
SE035	SETIA (2)	-	-	-	JL.TEUKU UMAR NO.36	TULUNG AGUNG	-	-	-	Aktif
AN026	ANEKA RIA	-	-	-	JL.WR.SUPRATMAN 78	TULUNGAGUNG	-	-	-	Aktif
LA018	LANCAR JAYA	-	-	-	JL.PETAK BARU B-19	JAK-BAR	-	-	-	Aktif
SA029	SAPTA JAYA	-	-	-	GG.TUMPUK NO.32(PS.PAGI	LAMA)JAKARTA	-	-	-	Aktif
GE008	GEMINI JAYA	-	-	-	MANYAR RAYA NO.8	SURABAYA	-	-	-	Aktif
TK014	TK.ANEKA PLASTIK	-	-	-	JL.PANDAN WANGI NO.132	RT.20,BLKPAPAN	-	-	-	Aktif
TK013	TK.TUNGGAL JAYA(BTL 109)	-	-	-	JL.A.YANI NO.17	BALIKPAPAN	-	-	-	Aktif
SI044	SIANTAR PLASTIK	-	-	-	JL.ANGKLUNG 1C PSR SEGIRI	SAMARINDA	-	-	-	Aktif
SA028	SAMI JAYA	-	-	-	JL.KARANG MENJANGAN NO.51	SURABAYA	-	-	-	Aktif
AG010	AGUNG WERDANA	-	-	-	JL.GAJAH MADA NO.21	JEMBER	-	-	-	Aktif
HE013	HENDRY(SISKA)	-	-	-	LEBAK INDAH UTARA 3B 12C	SURABAYA	-	-	-	Aktif
UD016	UD.NELA JAYA	-	-	-	TAMAN PONDOK JATI BLOK C	NO.2,SEPANJANG	-	-	-	Aktif
CA013	CAHAYA(TJIN HOUW)	-	-	-	JL.DARMO BARU BARAT I/57	SURABAYA	-	-	-	Aktif
LA017	LANI	-	-	-	GRIYA PERMATA,GEDANGAN	K4/27,SIDOARJO	-	-	-	Aktif
BI019	BINTANG MAKMUR	-	-	-	JL.CIBADAK NO.36	BANDUNG	-	-	-	Aktif
EX003	STATIONARY EXPRESS	-	-	-	JL.A.YANI KM 2,5 NO.14	BANJARMASIN	-	-	-	Aktif
SI039	SIU LIAN (CENDRAWASIH)	-	-	-	SIDOYOSO 1/36	SURABAYA	-	-	-	Aktif
TD001	TDS	-	-	-	JL.RUKO BANDENGAN INDAH	80 C/25,JAK-UT	-	-	-	Aktif
FE004	FEI	-	-	-	JL.KAPASAN 135	SURABAYA	-	-	-	Aktif
YO006	YOYOK (SP)	-	-	-	JL.KETINTANG IA/29	SURABAYA	-	-	-	Aktif
DI007	DIAN	-	-	-	JL.IST MENTARI REGENCY	B4/21,SIDOARJO	-	-	-	Aktif
ML001	ML JAYA	-	-	-	JL.KEMBANG JEPUN 55D	SURABAYA	-	-	-	Aktif
DE009	DCS(NOMO)	-	-	L	TELUK GONG JL.TERI J III NO.29 RT 6 RW 012	KEL:PEJAGALAN,KEC:PENJARINGAN,JAK-UT	-	0000-00-00	-	Aktif
LI014	LIMAR	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TO026	TOKO PRIMA	-	-	-	JL.JAWA NO.8	SITUBONDO	-	-	-	Aktif
AN025	ANEKA PENCIL ST(WANDI)	-	-	-	JL	JAKARTA	-	-	-	Aktif
GR005	GRAVINDO PRINT	-	-	-	JL.TAMBAK SEGARAN VIII/23	SURABAYA	-	-	-	Aktif
MI017	MICKEY MOUSE	-	-	-	JL.DR.SUTOMO NO.25	TUBAN	-	-	-	Aktif
KO009	KOSTA	-	-	-	-	JAKARTA	-	-	-	Aktif
SU044	SUKSES BERSAMA SEJAHTERA	-	-	-	JL.INDUSTRI N/71A	SEMARANG	-	-	-	Aktif
JA010	JAYA MAS STATIONERY	-	-	-	JL.KURIPAN NO.10 RT 3	BANJARMASIN	-	-	-	Aktif
UD015	UD.ADA DJADI	-	-	-	RUKO MANGGA DUA AA1/9-18	SURABAYA	-	-	-	Aktif
TE011	TEK HWA	-	-	-	JL.	SBY	-	-	-	Aktif
A 007	A FUNG	-	-	-	JL.	SEMARANG	-	-	-	Aktif
WA009	WANDI	-	-	-	PS. PAGI(JL.TELEPON SATU	III/18B)JKT	-	-	-	Aktif
PA014	PAK IMAM	-	-	-	-	SBY	-	-	-	Aktif
IB003	IBU TUN	-	-	-	-	SBY	-	-	-	Aktif
SU042	SURYA INDAH	-	-	-	KOMPLEK LODAN CENTER H2	JAKARTA	-	-	-	Aktif
BA016	BANDAR WANGI	-	-	-	GENTENG,	BANYUWANGI	-	-	-	Aktif
PA013	PANCA JAYA	-	-	-	RUKO MUTIARA PALEM BLOK	A-5/57,JAKBAR	-	-	-	Aktif
RA015	RAJAWALI	-	-	-	JL.RAJAWALI 9(PERUM DOSEN	UNS V)PALUR	-	-	-	Aktif
ED004	EDY	-	-	-	JL.	JAKARTA	-	-	-	Aktif
JI001	JIMMY STATIONARY	-	-	-	JL.MARGOMULYO PERMAI III/	168,SBY	-	-	-	Aktif
AN024	ANUGRAH	-	-	-	PERTK.SEMUT INDAH  E/6	SBY(3528054)	-	-	-	Aktif
BI018	BINTANG SURYA LIBERTY	-	-	-	JL.	JAKARTA	-	-	-	Aktif
PT015	PT.GRAFINDO ARTA PERSADA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
EX002	EXPEDISI SULUNG	-	-	-	JL.SULUNG NO.89	SURABAYA	-	-	-	Aktif
MI016	MITRA CABLE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
UD014	UD.DUTA STATONERY	-	-	-	JL.SONGOYUDAN 4	SURABAYA	-	-	-	Aktif
TO025	TOKO SAMPURNA	-	-	-	JL.PANGLIMA SUDIRMAN 242	TUBAN	-	-	-	Aktif
BA015	BALI SUMBER BERKAT	-	-	-	JL.TAMAN MUTIARA BLK B/4	MARJAYA-DPS	-	-	-	Aktif
HA017	HARAPAN INDAH	-	-	-	JL.MERTAYASA II NO.32	DPS-BALI	-	-	-	Aktif
KO008	KOH UN	-	-	-	JL. MEDAENG SELATAN GG.14	NO. 26 SURABAYA	-	-	-	Aktif
PT013	PT.HENINDO KARYA MANDIRI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
PA012	PAK AFAN	-	-	-	JL.	SBY	-	-	-	Aktif
DA006	DARMUJI	-	-	-	JL.PRAMUKA 158,BABAT	LAMONGAN	-	-	-	Aktif
SE034	SEMANGAT	-	-	-	JL.PASAR BARU	BANJARMASIN	-	-	-	Aktif
TE010	TERUS MAJU	-	-	-	JL.A.YANI KM 6,6 NO.30	BANJARMASIN	-	-	-	Aktif
MA027	MAJU MAPAN	-	-	-	JL.HASAN BASRI NO.47E,KA-	YU TANGI,B/SIN	-	-	-	Aktif
TO024	TOKO MANDIRI	-	-	-	JL.PANGLIMA SUDIRMAN 191	MADIUN	-	-	-	Aktif
PA011	PAK AFAN	-	-	-	JL.	SBY	-	-	-	Aktif
AN023	ANTOK	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SA027	SAMUDRA-CHANDRA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
HI002	HIDUP BARU	-	-	-	JL.WAHID HASYIM 174	PASURUAN	-	-	-	Aktif
AP006	APOTIK GRAHA	-	-	-	JL	SBY	-	-	-	Aktif
DA005	DANAMEL	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PA010	PAK AGUNG	-	-	-	DTC BLOK B/425-427 LT.1	SURABAYA	-	-	-	Aktif
JH001	JHON	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
KO007	KOH ALING	-	-	-	JL.VETERAN SEI BILO GG.7A	NO.48 RT.23	-	-	-	Aktif
AH003	AHOK	-	-	-	DUKUH PAKIS III/21	SURABAYA	-	-	-	Aktif
LU005	LU CHING	-	-	-	JL.	SIDOARJO	-	-	-	Aktif
NK001	NK TAPE	-	-	-	JL.RAYA PERANCIS,DAHAP	TANGERANG	-	-	-	Aktif
AG009	AGIM	-	-	-	JL.	JAKARTA	-	-	-	Aktif
ME008	MENTARINDO	-	-	-	JL.PETAK BARU II A/15	(GG.CAIHO) JKT	-	-	-	Aktif
SA026	SALES \"DWI INDAH\"	-	-	-	JL	SURABAYA	-	-	-	Aktif
PT014	PT DWI INDAH	-	-	-	JL.STASIUN KOTA 58C	SURABAYA	-	-	-	Aktif
TO023	TOKO PUTRA JAYA	-	-	-	JL.PASAR NO.10	BOJONEGORO	-	-	-	Aktif
FA010	FADJAR	-	-	-	JL.BRATANG GEDE VI G/52	SURABAYA	-	-	-	Aktif
UD013	UD.GUN-GUN ABADI	-	-	-	JETIS KULON I/22	SURABAYA	-	-	-	Aktif
PA009	AGUNG JAYA/PAK SLAMET	-	-	-	JL	MOJOKERTO	-	-	-	Aktif
RI007	RINGGIT PUTRA	-	-	-	JL.RAYA 572 ASEM BAGUS	SITUBONDO	-	-	-	Aktif
DI006	DINAS SOSIAL	-	-	-	JL.GAYUNG KEBONSARI 56B	SURABAYA	-	-	-	Aktif
HE012	HENDRA	-	-	-	KEMBANG JEPUN 162	SURABAYA	-	-	-	Aktif
TK012	TKL	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TO022	TOKO H.JONO	-	-	-	JL.	BABAT	-	-	-	Aktif
CI012	CITRA SARANA KREASI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
UN004	UNTUNG JAYA	-	-	-	PGS LT.4 E10-01	SURABAYA	-	-	-	Aktif
EK004	EKO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TO021	TOKO ACEH(WINOTO)	-	-	-	JL.RAYA 52A	GEMPOL	-	-	-	Aktif
FA009	FAJAR BARU	-	-	-	JL.RAYA GEMPOL 227	GEMPOL	-	-	-	Aktif
NA016	NABILA	-	-	-	PASAR BARU	TUBAN	-	-	-	Aktif
AM002	AMAN	-	-	-	JL.PANGLIMA SUDIRMAN 126	TUBAN	-	-	-	Aktif
MA026	MATAHARI	-	-	-	JL.GULUN NO.18	MADIUN	-	-	-	Aktif
JO008	JOHAN	-	-	-	KENJERAN II/21	SURABAYA	-	-	-	Aktif
SE033	SERASI MAJU MAKMUR	-	-	-	KOMPLEK DHI BLOK SS NO.25	JAKARTA	-	-	-	Aktif
A 006	A BUN	-	-	-	JL	-	-	-	-	Aktif
Y.001	Y.S	-	-	-	JL	SBY	-	-	-	Aktif
CT001	CTG	-	-	-	JL.GAMBANG II/64A	JAKARTA	-	-	-	Aktif
TR012	TRIJAYA KERTAS	-	-	-	JL.RAYA MARGOMULYO INDAH	NO.31,SBY	-	-	-	Aktif
H.002	H.A.MUKRI	-	-	-	KEMENTRIAN AGAMA	MOJOKERTO	-	-	-	Aktif
DI005	DIM	-	-	-	JL.	LASEM	-	-	-	Aktif
TE009	TERUS LANCAR	-	-	L	JL.GATOT SUBROTO 59	MALANG	-	0000-00-00	-	Aktif
BP008	BP.HARYADI /PT.ANATA RAYA	-	-	-	JL.ADI SUMARMO NO.125	KARTASURA-SRKTA	-	-	-	Aktif
LI013	LILIK	-	-	-	-	SURABAYA	-	-	-	Aktif
US004	USMAN(GUNINDO)	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TO020	TOMINDO UTAMA CEMERLANG	-	-	-	-	SBY	-	-	-	Aktif
SA025	SAKURA/3S STATIONARY	-	-	-	-	SURABAYA	-	-	-	Aktif
CA012	CAHAYA TERANG GEMILANG	-	-	-	-	JAKARTA	-	-	-	Aktif
TO019	TOKO GADING MURNI	-	-	-	JL.TANJUNG PERAK TMR 540-	542,SURABAYA	-	-	-	Aktif
YO005	YOYOK /PANCA	-	-	-	JL.WIGUNA X/2	SBY	-	-	-	Aktif
TO018	TOPLA FILE SYSTEM	-	-	-	RUKO PELANGI BLOK G NO.29	JAK-BAR	-	-	-	Aktif
EN006	ENG KWANG	-	-	-	JL.DARMA HUSADA INDAH UT	BLOK U IX/12	-	-	-	Aktif
DW003	DWI JAYA /AHINDO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
PT012	PT.SOLO MURNI	-	-	-	JL.KALIANAK 55	SURABAYA	-	-	-	Aktif
PU015	PUSPITA/S2	-	-	-	RK PLAZA NAPAN RD-8 STAN	TC NO.5 BLKPPN	-	-	-	Aktif
CV005	CV.SURYA GEMILANG	-	-	-	JL.	SURABAYA	-	-	-	Aktif
CV004	CV.MITRA	-	-	-	KOMP VILLA CIMONE GARDEN	BLOK B NO.1 JKT	-	-	-	Aktif
A 005	A HO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
IR003	IRA	-	-	-	JL.ARGO PURO 20	SURABAYA	-	-	-	Aktif
DI004	DJAGO	-	-	-	JL.MASJID NO.84	MOJOSARI	-	-	-	Aktif
ST006	STIKES YARSES	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BP006	BP.AGUNG / KODIN	-	-	-	JL.MANGGA 220,DS SRUNI	GEDANGAN,SDA	-	-	-	Aktif
H.001	H.SOBIR	-	-	-	JL.	SURABAYA	-	-	-	Aktif
YA002	YAYANG	-	-	-	JL.	JAKARTA	-	-	-	Aktif
CV003	CV.HANIKA JAYA	-	-	-	JL.KRUKAH SLTN VIIB/10	SURABAYA	-	-	-	Aktif
BU013	BUDI	-	-	-	JL.KALI RUNGKUT 27,RUKO	RUNGKUT C-78	-	-	-	Aktif
SE032	SEGI MAS	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TK011	TK BHAKTI / JIMMY	-	-	-	JL.RAYA KARANGLO 94-104	SINGOSARI	-	-	-	Aktif
KO006	KOPERASI KRYW TJIWI KIMIA	-	-	-	JL.RAYA SBY-MJKERTO KM.44	SURABAYA	-	-	-	Aktif
PA008	PAK ANIS	-	-	-	JL.BRO MELIA 12(GRAHA TIR	TA WARU),SBY	-	-	-	Aktif
SE031	SETIA JAYA	-	-	-	JL.KH DEWANTORO	KRIAN	-	-	-	Aktif
DW002	DWI STAR	-	-	-	SURI MULIA BLOK E/5	SURABAYA	-	-	-	Aktif
US003	USUN	-	-	-	JL.KRANGGAN NO.112	SURABAYA	-	-	-	Aktif
PA007	PANCA WARNA	-	-	-	PS.TURI LT.I BLOK H 20-22	SURABAYA	-	-	-	Aktif
BA014	BAPAK.SUALA	-	-	-	-	PORONG	-	-	-	Aktif
BI017	BINTANG JAYA /PERTIWI	-	-	-	JL.KEPUTRAN 55	SURABAYA	-	-	-	Aktif
UD012	LANGGENG	-	-	-	JL.KEMBANG JEPUN 131	SBY(3524986)	-	-	-	Aktif
AN022	ANUGRAH STATIONARY	-	-	-	JL.PEMUDA NO.46	MOJOKERTO	-	-	-	Aktif
PA006	PAK ISMAIL	-	-	-	-	-	-	-	-	Aktif
DU014	DUTA ILAHI 2	-	-	-	JL.DR.SUTOMO NO.30	REMBANG	-	-	-	Aktif
CH001	CHIAWU	-	-	-	JL.KENJERAN 475-481 BLK C	-2 RUJO FIRA 51	-	-	-	Aktif
TO017	TOKO PRIMA 2	-	-	-	JL.EYANG SAMBU 61	LASEM	-	-	-	Aktif
CE001	CERIA	-	-	-	JL.RAYA LASEM 97	LASEM	-	-	-	Aktif
SA024	SANJAYA	-	-	-	SEMOLO WARU TENGAH I/14	SURABAYA	-	-	-	Aktif
RO005	ROCHIM	-	-	-	KEDUNG KENDO/KAYEN RT 14	RW 5 CANDI-SDA	-	-	-	Aktif
AT002	ATSASEJATI.CV	-	-	-	PURI INDAH BLOK BA 06	SIDOARJO 61224	-	-	-	Aktif
L.001	L.CANDRA (S-529)	-	-	-	JL.PAHLAWAN,RUKO PERMATA	KALTIM/26  SMD	-	-	-	Aktif
GE007	GE TAPE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
HA016	HAUSIEN	-	-	-	JL.PLOSO I/32	SURABAYA	-	-	-	Aktif
A'001	A'AN	-	-	-	-	-	-	-	-	Aktif
MU012	MULAWARMAN	-	-	-	JL.DR.SOETOMO NO.43	SAMARINDA	-	-	-	Aktif
S.002	S.CANDRA (S.55)	-	-	-	JL.KH.M.KHALID NO.3 RT.12	SAMARINDA	-	-	-	Aktif
ED003	EDDY STATIONARY	-	-	-	JL.SUKOMANUNGGAL JAYA VI/	SURABAYA	-	-	-	Aktif
FA008	FAJAR TERBIT (HERO)	-	-	-	JL.PASAR BARU 43 A	BANJARMASIN	-	-	-	Aktif
DE008	DEA	-	-	-	PERINTIS KEMERDEKAAN 31 B	BANJARMASIN	-	-	-	Aktif
OL002	OLIMPIC(AS 70)	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
KA012	KARUNIA/BWG	-	-	-	JL.RAYA RUKO N24	ROGOJAMPI/BWG	-	-	-	Aktif
SE030	SENTOSA BARU	-	-	-	DEPAN POM BENSIN CLURING	BANYUWANGI	-	-	-	Aktif
PT011	PT.BENOFARM	-	-	-	JL.DARMO KALI 76	SURABAYA	-	-	-	Aktif
DI003	DIAMOND/INTAN	-	-	-	JL.SUDIRMAN NO.22	SUMENEP	-	-	-	Aktif
WA008	WAHYU ARIES STATIONARY	-	-	-	PROYEK PSR PAGI LAMA LT.	DSR BLOK SI 45	-	-	-	Aktif
DU013	DUTA ILAHI	-	-	-	JL.SUNAN BONANG NO.97	LASEM	-	-	-	Aktif
MI015	MIRAGE INDONESIA	-	-	-	JL.MULYOSARI PRIMA UT VII	SURABAYA	-	-	-	Aktif
PT004	PT.GLOBAL PRATAMA ABADI	-	-	-	PROF DR.LATUMENTEN  NO.50	KOMP RCL H1 JKT	-	-	-	Aktif
CI011	CITY STATIONARY MART	-	-	-	JLN.TURNA JAYA NO.11	JEMBER	-	-	-	Aktif
PA005	PAK MAKSUM	-	-	-	JL.BAGONG GINAYAN  5 NO.	SURABAYA	-	-	-	Aktif
TI007	TITI	-	-	-	SUTOREJO UTARA 4/27	SURABAYA	-	-	-	Aktif
FE003	FERRY	-	-	-	CRIS KENCANA	SURABAYA	-	-	-	Aktif
PT005	PT.COLINDO PERKASA ABADI	-	-	-	-	SURABAYA	-	-	-	Aktif
SO003	SODIQ	-	-	-	-	SIDOARJO	-	-	-	Aktif
AG008	AGUS LAY'S	-	-	-	-	JAKARTA	-	-	-	Aktif
HE011	HENDRI	-	-	-	-	JAKARTA	-	-	-	Aktif
JO007	JOYO MULYO	-	-	-	JL.KENJERAN	SURABAYA	-	-	-	Aktif
GU010	GUNUNG ARTA	-	-	-	RUNGKUT	SURABAYA	-	-	-	Aktif
CA011	CAMBRIDEE	-	-	-	JL.SATELIT INDAH CN1	SURABAYA	-	-	-	Aktif
DA004	DAVID	-	-	-	-	SURABAYA	-	-	-	Aktif
SI043	SING2 / HARTONO	-	-	-	KS TUBUN GG2 DAMAI 4/6	BANJARMASIN	-	-	-	Aktif
DU012	DUTA SARANA  PRATAMA	-	-	-	INDRALOKA II H1 NO.1857	JAKARTA	-	-	-	Aktif
BA013	BAHAGIA TEGUH	-	-	-	JL.BELANDONGAN 24B TAMBO-	RA IV JAK-BAR	-	-	-	Aktif
KA011	KARYA UNGGUL	-	-	-	RAYA DUKU KUPANG 125	SURABAYA	-	-	-	Aktif
SU051	SUSAN / ARTHA PRIMA	-	-	-	JL. DR.SURATMO 24	SEMARANG	-	-	-	Aktif
CI010	CIPTA GEMILANG NUSANTARA	-	-	-	-	SURABAYA	-	-	-	Aktif
MA025	MAJU	-	-	-	-	SURABAYA	-	-	-	Aktif
JO006	JOYKO	-	-	-	PANTAI INDAH SLT I,DC-3	JAK-UT	-	-	-	Aktif
ZE001	ZELVI	-	-	-	JUWINGAN 102A	SURABAYA	-	-	-	Aktif
UD011	UD.WAHID	-	-	-	-	JAKARTA	-	-	-	Aktif
AN021	ANDRE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
MI014	MITRA	-	-	-	JL.YOS SUDARSO NO.195	JAJAG/BWI	-	-	-	Aktif
BE007	BERKAT ANDALAN KERTAS	-	-	-	MARGOMULYO 44 BLOK DD/22	SURABAYA	-	-	-	Aktif
VI006	VIVI.CO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AR005	ARI HARTANTO	-	-	-	PURNAWIRA XI/2/PADANG SA-	MBIAN KLOD/DPS	-	-	-	Aktif
WA007	WAYAN / IYAN KUTA	-	-	-	WIBISANA BARAT 91	KUTA-BALI	-	-	-	Aktif
GM001	GMC	-	-	-	JL.	JAKARTA	-	-	-	Aktif
HE010	HENDRO	-	-	-	JL.TAMBAK REJO 62	SURABAYA	-	-	-	Aktif
AS010	ASIA TIMUR RAYA	-	-	-	RUKO HARMONI MAS D-2	JAKARTA	-	-	-	Aktif
AR004	ARTA KARYA UTAMA	-	-	L	JL.ANTA SURA NO.27	DENPASAR	-	0000-00-00	-	Aktif
TI008	TIRTA BUANA	-	-	-	JL.PAGARSIH NO.173	BANDUNG	-	-	-	Aktif
WA006	WAWAN	-	-	-	JOJORAN IIIE DALAM 144	SURABAYA	-	-	-	Aktif
SI042	SIKIN	-	-	-	JOJORAN IIIE DALAMNO.5	SURABAYA	-	-	-	Aktif
SW001	SWISS BARU	-	-	-	JL.NIAGA UTARA 20/A	SAMARINDA	-	-	-	Aktif
SI041	SINAR MULIA	-	-	-	JL.KRANGGAN NO.14	SURABAYA	-	-	-	Aktif
PA004	PASIN	-	-	-	BANDENGAN UTR GG.BUNTEK	85A/16 JKT	-	-	-	Aktif
SL002	SLAMET	-	-	-	JL.	SURABAYA	-	-	-	Aktif
IS002	ISMANTO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
GA006	GALAKSI	-	-	-	JL.KOLONEL SUNANDAR NO.41	BLORA	-	-	-	Aktif
CA010	CASIO	-	-	-	JL	SURABAYA	-	-	-	Aktif
EL004	ELANG MAS/JOHAN	-	-	-	JL.BRATANG WETAN	SURABAYA	-	-	-	Aktif
PT010	PT.FABER CASTEL INDONESIA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
KU008	KURNIA CIPTA	-	-	-	JL.SIMO GUNUNG III/18	SURABAYA	-	-	-	Aktif
AS009	ASIEK PLASTIK	-	-	-	LEBAK INDAH REGENCY F-7	SURABAYA	-	-	-	Aktif
AS008	ASIUNG	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AP005	APAU (BUDI ST)	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TK010	TK.RIDLO	-	-	-	GRIYO BAYANGKARA A NO.20	SURABAYA	-	-	-	Aktif
SI040	SINAR MAS	-	-	-	JL.MULYOSARI MAS BLK F12A	SURABAYA	-	-	-	Aktif
ED002	EDWIN/LIANA TART	-	-	-	JL.KEDUNG COWEK	SURABAYA	-	-	-	Aktif
TA007	TANOKO	-	-	-	LIK	SEMARANG	-	-	-	Aktif
LA016	LANGGENG	-	-	L	JL.GANG LOMBOK BARAT NO.7	SEMARANG	-	0000-00-00	-	Aktif
BP005	BP. YUSUP/ZAENI	-	-	-	MANGGA DUA BLK A9/2	SURABAYA	-	-	-	Aktif
SA023	SARINAH	-	-	-	JL.RAJAWALI 81	BOJONEGORO	-	-	-	Aktif
A 004	A JUN	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PT009	PT.SUMBER HIDUP CEMERLANG	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SU050	SUMBER NIAGA	-	-	-	PERTOKOAN DUPAK MEGAH A18	SURABAYA	-	-	-	Aktif
CV002	CV.SINAR INTI MAKMUR ABD	-	-	-	JL.	SURABAYA	-	-	-	Aktif
KM001	KMB	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BA012	BATAVIA TRI NUSA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SE029	SEMBILAN-SEMBILAN ST	-	-	-	JL.	JAKARTA	-	-	-	Aktif
YO004	YONO/P.DIMAN	-	-	-	GROGOLAN MOJOAGUNG	SURABAYA	-	-	-	Aktif
LI012	LITA / BERRY	-	-	-	JL.SINAR GEDANGAN BLOK D	NO.2 SBY	-	-	-	Aktif
SA022	SAHABAT SEJATI	-	-	-	JL.KOMP DHI BLOK A/ 19	JAKARTA	-	-	-	Aktif
VA003	VALENTINE	-	-	-	PSR BLAURAN  BARU LNT 1	SURABAYA	-	-	-	Aktif
SI038	SILVI	-	-	-	JL.JAPRI ZAMZAM TK 89	BANJARMASIN	-	-	-	Aktif
DU011	DUNIA TISSUE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
LA015	LAY'S	-	-	-	JL.PERNIAGAAN TMR NO.18A	JAK-BAR	-	-	-	Aktif
AH002	AHIE	-	-	-	TAMAN PONDOK JATI CC 18	TAMAN-SEPANJANG	-	-	-	Aktif
CI009	CIPTA JAYA(TOKO MERPATI)	-	-	L	JL.SARANGAN NO.21E	MALANG	-	0000-00-00	-	Aktif
MU015	MULTI JAYA ABADI	-	-	-	JL.TAMBAK ADI 142-16	SURABAYA	-	-	-	Aktif
AG007	AGUS/D.P	-	-	-	JL.PETA BRT RK CBP BLK F	36,KALIDERES.	-	-	-	Aktif
AS007	AS'AD	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AG006	AGUS	-	-	-	DESA WANGKIT	LAMONGAN	-	-	-	Aktif
KA010	KAWAN MULIA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SU049	SUKSES BERSAMA/AHOK	-	-	-	JL.BANDENGAN SEL.43/I-12	JAKARTA UTARA	-	-	-	Aktif
JO005	JONATHAN ART STUDIO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
UD010	UD.RAHMAT	-	-	-	JL.PATIMURA 18	BOJONEGORO	-	-	-	Aktif
WI010	WIJAYA PERSADA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
UD009	UD.88	-	-	-	JL.NOJA XXIX/51	DENPASAR	-	-	-	Aktif
BU012	BUDI	-	-	-	TAMAN SUKO ASRI D 27	SEPANJANG	-	-	-	Aktif
TR011	TRIJAYA MAS	-	-	-	JL.	SURABAYA	-	-	-	Aktif
CI008	CITRA SUKSES	-	-	-	KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
US002	USAHA MANDIRI	-	-	-	DTC BLK LD B 579(RMJL.TAL	AS 1/11) SBY	-	-	-	Aktif
GE006	GEMA SARANA	-	-	-	JL.DIPENOGORO 108	BOJONEGORO	-	-	-	Aktif
AN020	ANALISA	-	-	-	JL.KH.HASYIM ASY'ARI 1	BOJONEGORO	-	-	-	Aktif
CA009	CALVIN COLLECTION	-	-	-	JL.	JAKARTA	-	-	-	Aktif
JA009	JAI	-	-	-	JL.	PORONG	-	-	-	Aktif
HA015	HANDAYANI	-	-	-	JL.JAGIR WONOKROMO WTN 22	SURABAYA	-	-	-	Aktif
LG001	LGS	-	-	-	JL.	PANGKALANBUN	-	-	-	Aktif
LE003	LESTARI GIAT JAYA	-	-	-	JL.TENIS RAYA NO 8-9,CENG	KARENG INDAH	-	-	-	Aktif
LI011	LIBERTY	-	-	-	JL.PEMUDA 19	KEDIRI	-	-	-	Aktif
SU048	SUMBER BARU	-	-	-	SERSAN HARUN 28	MALANG	-	-	-	Aktif
HA014	HARAPAN SEJATI	-	-	-	KUTUK BARAT 70 SIDOKARE	SIDOARJO	-	-	-	Aktif
DU010	DUTA WARNA GRACIA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TK009	TK.SINAR MULIA	-	-	-	JL.GAJAH MADA PS.BARU 14A	TUBAN	-	-	-	Aktif
TK008	TK.ATOM	-	-	-	JL.PASAR 4	BOJONEGORO	-	-	-	Aktif
TK007	TK. BORSALINO	-	-	-	JL.TRUNOJOYO NO.3	BOJONEGORO	-	-	-	Aktif
TK006	TK. RUT JAYA	-	-	-	JL.J.A.SUPRAPTO 217-221	BOJONEGORO	-	-	-	Aktif
PT007	PT.OJI PRINTECH INDONESIA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SI037	SINAR HARAPAN MLG	-	-	L	JL.SULFAT RUKO BMW B-3	MALANG	-	0000-00-00	-	Aktif
AN019	ANIS	-	-	-	JL.	LAMONGAN	-	-	-	Aktif
LA014	LASMIADI	-	-	-	JL.PERUM BAYANGKARA	SEPANJANG	-	-	-	Aktif
WI009	WIE WIE/SUMBER LANCAR	-	-	-	JL.RUNGKUT ASRI TMR 15/70	SURABAYA	-	-	-	Aktif
YS001	YS STATIONERY	-	-	-	JL DUKUH SETRO 12/57	SURABAYA	-	-	-	Aktif
PT006	PT.SUMBERTAMAN KERAMIK	-	-	-	JL.LUMAJANG KM 5	PROBOLINGGO	-	-	-	Aktif
UD008	UD.RESMI ABADI JAYA	-	-	-	JL.RAYA BERINGKIT MENGWI	DPS-BALI	-	-	-	Aktif
ZA001	ZAENURI	-	-	-	JL.BURNEI	MADURA	-	-	-	Aktif
WI008	WIBOWO	-	-	-	JL.JAGIR WONOKROMO WTN/06	SURABAYA	-	-	-	Aktif
HU001	HUDA	-	-	-	JL.BULAK KENJERAN GG IIA	SURABAYA	-	-	-	Aktif
CA008	CAKRAWALA	-	-	-	JL.RAYA TULANGAN NO.41	SIDOARJO	-	-	-	Aktif
TK005	TK.BEDAK 8	-	-	-	JL.KOPRAL USMAN 12A	MALANG	-	-	-	Aktif
AN018	ANEKA STATIONERY	-	-	-	JL.GATOT SUBROTO III/85	MALANG	-	-	-	Aktif
BA011	BASORI	-	-	-	JL.TEBEL NO.11A	GEDANGAN	-	-	-	Aktif
TK004	TK.ELITE	-	-	-	JL.LETKOL SUMARJO.82	MOJOKERTO	-	-	-	Aktif
SY004	SYAHID PUTRA	-	-	-	JL.PULAU BIAK NO.11A	DENPASAR - BALI	-	-	-	Aktif
PU014	PUTRA DUA	-	-	-	JL.GOTONG ROYONG,BABAT	LAMONGAN	-	-	-	Aktif
BI016	BINTANG SATYA KENCANA	-	-	-	JL.MARGOMULYO 44 BLK/KK22	SURABAYA	-	-	-	Aktif
PA003	PANEN JAYA INDAH	-	-	L	JL.PULAU BANDA NO.8	DENPASAR - BALI	-	0000-00-00	-	Aktif
ID001	IDA JAYA	-	-	-	JL.RAYA SEMPIDI BR.PANDE	DENPASAR - BALI	-	-	-	Aktif
TK003	TK.SYAHID PUTRA	-	-	-	JL.P.BIAK NO.11A	DENPASAR - BALI	-	-	-	Aktif
RI006	RIZKY JAYA	-	-	-	STAND NO.11 DLM PSR	TABANAN-BALI	-	-	-	Aktif
MG002	MGS	-	-	-	JL. WAHID HASYIM 177	JOMBANG	-	-	-	Aktif
NU003	NUR HIKMAH	-	-	-	BRATANG BESAR	SURABAYA	-	-	-	Aktif
LA013	LANCAR JAYA	-	-	-	JL.LAWU 1/47	MOJOKERTO	-	-	-	Aktif
TO016	TOKO FAUZAN	-	-	-	PS. JAPANAN	PORONG	-	-	-	Aktif
BA010	BAMBANG	-	-	-	BREBEK INDUSTRI 1B/13	SURABAYA	-	-	-	Aktif
SA021	SAUD	-	-	-	DS. TUNGGUN	LAMONGAN	-	-	-	Aktif
HA013	HARYANTO	-	-	-	BALONG WONO TROWULAN	MOJOKERTO	-	-	-	Aktif
MU014	MUJIB	-	-	-	JL.SUKOLEGO RT 10	SURABAYA	-	-	-	Aktif
TK002	TK. SISWA DUA	-	-	-	PS. KRIAN	KRIAN	-	-	-	Aktif
SO002	SONI	-	-	-	JL. TAMBAK WEDI BARU/119	SURABAYA	-	-	-	Aktif
RO004	ROZAK	-	-	-	JL. SUKOLEGO	SURABAYA	-	-	-	Aktif
SU046	SUPONO	-	-	-	JL. SUKOLEGO RT 04	SURABAYA	-	-	-	Aktif
IM003	IMAM	-	-	-	JL.SUKOLEGO SEPANJANG	SURABAYA	-	-	-	Aktif
NE002	NEOTEXINT	-	-	-	JL	SURABAYA	-	-	-	Aktif
\"A001	\"AAA\"	-	-	-	JL.	SURABAYA	-	-	-	Aktif
UD007	UD. CIPTA PRIMA NUSANTARA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
HO002	HOKINDO JAYA	-	-	-	JL. KAPUK UTR I/168	JAKARTA	-	-	-	Aktif
SI036	SINAR KATULISTIWA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
TU006	TUNAS BARU	-	-	-	PRYK PS.PG.LM.LT2S2/55-56	JAKARTA	-	-	-	Aktif
KU007	KURNIA JAYA	-	-	-	JL. UNTUNG SEROPATI 500A	SEMARANG	-	-	-	Aktif
TO015	TOKO ORLANE	-	-	-	JL.SAM RATULANGI NO.96-98	MANADO	-	-	-	Aktif
TR010	TRINUNGGAL	-	-	-	KOMP PURI DELTA MAS	JAKARTA-UTARA	-	-	-	Aktif
SI035	SINAR ABADI JAYA	-	-	-	PS.BARU NO.11	BANJARMASIN	-	-	-	Aktif
RI005	RIKKY	-	-	-	DARMO PERMAI SELATAN X/24	SURABAYA	-	-	-	Aktif
JO003	A CAI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
HA012	HAKKIM STATIONERY	-	-	-	JL.KALI MALANG	SURABAYA	-	-	-	Aktif
SI034	SINAR MAKMUR	-	-	-	JL.PS PAGI 84	JAKARTA	-	-	-	Aktif
BI015	BINTANG JAYA	-	-	-	JL.PS PAGI I NO.8	JAKARTA	-	-	-	Aktif
CA007	CAHAYA GEMILANG	-	-	L	JL. MALAKA RAYA NO.38A	JAKARTA	-	0000-00-00	-	Aktif
FR001	FRANGKO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
P.002	P.D. EMBUN PAGI	-	-	-	JL.CAIHO NO.9  (PS PAGI)	JAKARTA	-	-	-	Aktif
BE006	BERKAT DAMAI	-	-	-	JL.PS GELAP NO.5	JAKARTA	-	-	-	Aktif
UD006	UD KURNIA	-	-	-	JL. SIMOKERTO 92	SURABAYA	-	-	-	Aktif
SA020	SAPTA	-	-	-	RUKO KLAMPIS 21 BLK H/9	SURABAYA	-	-	-	Aktif
HE009	HERMANTO	-	-	-	KAPAS TNGH RAYA H/18-20	GENUK INDAH,SMG	-	-	-	Aktif
AG005	AGUAN	-	-	-	JL.	JAKARTA	-	-	-	Aktif
DR001	DRAGON PAN PACIFIC	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AA002	AAY	-	-	-	JL.PRAMUKA KM 6,KOMP SI	BLK B/5 / BJM	-	-	-	Aktif
MU013	MULTI STAR	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SE028	SEJATI JAYA	-	-	-	PETEMON BARAT 217	SURABAYA	-	-	-	Aktif
SU045	SURYA JAYA	-	-	-	KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
SI033	SINAR MANDIRI	-	-	-	GG SENTONG MARGOMULYO	SURABAYA	-	-	-	Aktif
UN003	UNTANA	-	-	-	JL INDUSTRI LIK XX/903	SEMARANG	-	-	-	Aktif
BA009	BAMBANG BWG	-	-	L	UTR MASJID PASINAN SINGO	JURUH,ROGOJAMPI	-	0000-00-00	-	Aktif
PE010	PELITA CANDLES	-	-	-	JL.	SURABAYA	-	-	-	Aktif
ME019	MERCY	-	-	-	JL.UNDAAN WETAN V/8-10	SURABAYA	-	-	-	Aktif
AD005	ADIN	-	-	-	RUNGKUT ASRI TIMUR IV/29	SURABAYA	-	-	-	Aktif
IW001	IWAN	-	-	-	JL.MANGGA 3 NO 401 14/27	TJ REDEP-BERAU	-	-	-	Aktif
SA019	SARI JAYA	-	-	-	JL.PASAR BARU	BANJARMASIN	-	-	-	Aktif
SM001	SMP	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AK002	AKEMI BALI CRAFT/NYOMAN S	-	-	-	JL. BANDAPURA I/1	DENPASAR-BALI	-	-	-	Aktif
SA018	SAMUDRA	-	-	-	JL.LETJEND SUPRAPTO NO11B	WARU,SIDOARJO	-	-	-	Aktif
EK003	EKA KARYA UTAMA	-	-	-	JL.SIMO GUNUNG BRT II/12	SURABAYA	-	-	-	Aktif
CA006	CARAVAN PLASTIK INDUSTRY	-	-	-	JL.PS TURI	SURABAYA	-	-	-	Aktif
VI005	VIKO STATIONERY	-	-	-	JL. KALI MALANG,	SURABAYA	-	-	-	Aktif
MI013	MING MING	-	-	-	JL	SEMARANG	-	-	-	Aktif
ME018	MEGA KERTAS / ANDREW	-	-	-	JL. KAPASAN 172	SURABAYA	-	-	-	Aktif
MI012	KOH MING MING	-	-	-	MERUYA KAV DKI BLOK 30/4	JAK-BAR	-	-	-	Aktif
SU043	SURYA NUSANTARA	-	-	-	JL. DUKUH KPG TMR XIIA/68	SURABAYA	-	-	-	Aktif
AU002	AULIA	-	-	-	JL.KEBONSARI TENGAH 71	SURABAYA	-	-	-	Aktif
IN007	INTI BINA MANDIRI	-	-	-	JL. MARGOMULYO 44/DD 22	SURABAYA	-	-	-	Aktif
TO014	TOKO RATNA	-	-	-	PUCANG ANOM 42	SURABAYA	-	-	-	Aktif
VI004	VICTORY MAS	-	-	-	JL.JEMUR SARI SLT IV/29	SURABAYA	-	-	-	Aktif
MI011	MINOLTA /SINAR ULTRA	-	-	-	BANJARMASIN NO.30	BANJARMASIN	-	-	-	Aktif
TI006	TIGA JAYA (BJM)	-	-	-	JL.NIAGA UTARA NO.40	BANJARMASIN	-	-	-	Aktif
BU011	BUDIANA	-	-	-	JLN. PASAR BARU 68	BANJARMASIN	-	-	-	Aktif
OL001	OLYMPIC	-	-	-	JL. NIAGA UTARA NO.14 A	BANJARMASIN	-	-	-	Aktif
JA008	JAYA SANTOSO (ALAT TULIS)	-	-	-	JL.SERSAN HARUN(LT23-24)	MALANG	-	-	-	Aktif
ME017	MEKAR SARI	-	-	-	PASAR LARANGAN NO 106-108	SIDOARJO	-	-	-	Aktif
CI007	CIRCLE TECHNOLOGY	-	-	-	JL	SURABAYA	-	-	-	Aktif
IN006	INDOGIFT	-	-	-	RUKO DAAN MOGOT BARU BLOK	LC 2 NO 6 JKT	-	-	-	Aktif
BA008	BARU	-	-	-	JL MOJOPAHIT 31	SIDOARJO	-	-	-	Aktif
BU010	BURSA MAHASISWA	-	-	-	JL.KALIMANTAN NO 61 A	JEMBER	-	-	-	Aktif
PE009	PELANGI (RUNGKUT)	-	-	-	JL.RUNGKUT KIDUL NO 2	SURABAYA	-	-	-	Aktif
PE008	PELANGI	-	-	-	JL GAJAH MADA NO.47-49	SIDOARJO	-	-	-	Aktif
AR003	ARIO/CIK LIEP	-	-	-	JL, DINOYO	SURABAYA	-	-	-	Aktif
LI010	LION	-	-	-	GRAHA FAMILY BLOK B /63	SURABAYA	-	-	-	Aktif
AN017	ANEKA KARYA UTAMA	-	-	-	SIMO GUNUNG BARAT TQL 11	SURABAYA	-	-	-	Aktif
HE008	HERO SBY	-	-	-	JL	SURABAYA	-	-	-	Aktif
YO003	YONG	-	-	-	JL. KENJERAN 235	SURABAYA	-	-	-	Aktif
YE001	YENNY	-	-	-	GALAXI BUMI PERMAI L5/3A	SURABAYA.	-	-	-	Aktif
BP004	BP. ANSARI	-	-	-	JL.	SBY.	-	-	-	Aktif
AN016	ANUGRAH STATIONERY	-	-	-	KOMP.RUKO DHI BLOK UU/61	JAKARTA UTARA	-	-	-	Aktif
LI009	LILI	-	-	-	RM.BATAS KOTA JL.TIM-TIM	OESAPA,KUPANG	-	-	-	Aktif
MA024	MAHKOTA	-	-	-	JL. RAYA 53 MUKA GNI	TANGGUL	-	-	-	Aktif
PU013	PUTRA REJO	-	-	-	JL.	TANGGUL	-	-	-	Aktif
YO002	YOUNG YOUNG	-	-	L	JL. KH.WAHID HASYIM NO:3	JEMBER	-	0000-00-00	-	Aktif
TO013	TOKO RAYA	-	-	-	JL.	PASURUAN	-	-	-	Aktif
BP003	BP. MOKO	-	-	-	JL. DUKUH KUPANG,	SBY	-	-	-	Aktif
LA012	LAVANZA/LUSI	-	-	-	JL.GREEN VILLE BLOK BG/26	JAKARTA BARAT	-	-	-	Aktif
DE007	DEVITA	-	-	-	JL. GATOT SUBROTO NO:11	JEMBER	-	-	-	Aktif
VI003	VITA	-	-	-	GAJAH MADA 236,	GENTENG	-	-	-	Aktif
TE008	TELASIH BARU	-	-	-	P.BESAR SUDIRMAN 67	SITUBONDO	-	-	-	Aktif
SA017	SAHABAT JAYA	-	-	-	DIPONEGORO 97,	SITUBONDO	-	-	-	Aktif
SE027	SENTOSA JAYA	-	-	-	PASAR LARANGAN	SIDOARJO	-	-	-	Aktif
AG004	AGAPE	-	-	-	JL.RY THAMRIN BEDAK 22	LAWANG	-	-	-	Aktif
SU041	SURYA AGUNG	-	-	-	PASAR TURI,	SURABAYA	-	-	-	Aktif
YU003	YUWONO SUTANTO	-	-	-	GADING PANTAI BESAR 7	SBY	-	-	-	Aktif
BI014	BINTANG TIMUR	-	-	-	JL.KAPUK KAMAL NO.40 BLK-	L27,JAK-UT	-	-	-	Aktif
PI005	PILAR MAS	-	-	-	DHI BLOK TT NO.43	JAKARTA	-	-	-	Aktif
UD005	UD.MITRA MANDIRI	-	-	-	KOMP.RUKO MANGGA DUA	SURABAYA	-	-	-	Aktif
EX001	EXECUTIVE PRATAMA	-	-	-	KOM.BANGUN KAPUK MAS CI/2	JAKARTA-BARAT	-	-	-	Aktif
HA011	HAU SIEN	-	-	-	JL.	SURABAYA	-	-	-	Aktif
GA005	GADING STATIONERY	-	-	-	JL.	JAKARTA	-	-	-	Aktif
RE009	RESTU JAYA	-	-	-	JL.PETEMON III/168-B,	SURABAYA	-	-	-	Aktif
IR002	IRENE	-	-	-	PRIMA/RESIDEN SUDIRMAN	SURABAYA	-	-	-	Aktif
MI010	MING CHEN	-	-	-	JL.JAGIR SIDOMUKTI III/19	SURABAYA	-	-	-	Aktif
PI004	PITJAYA	-	-	-	JL.SIMOKATRUNGAN	SURABAYA	-	-	-	Aktif
MA023	MASTER	-	-	-	JL.	LOMBOK	-	-	-	Aktif
PT003	PT FABERINDO PERKASA	-	-	-	JL	SBY	-	-	-	Aktif
WI005	WINARTO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
ME016	MEI LAN	-	-	-	JL.	SEMARANG	-	-	-	Aktif
MA022	MAS CHANDRA	-	-	-	SEMOLOWARU ELOK BLK-AD/5	SURABAYA	-	-	-	Aktif
LI008	LIM YUMING	-	-	-	JL.KUTISARIINDAH BRT V/72	SURABAYA	-	-	-	Aktif
NI004	NIAGA PERMAI	-	-	-	JL.NIAGA BARU NO.49C	SAMARINDA	-	-	-	Aktif
TI005	TINA (NO.14)	-	-	-	GATOTSUBROTO TIMUR I RT27	BANJARMASIN	-	-	-	Aktif
TU005	TUNAS JAYA	-	-	-	KERTA JAYA VII RAYA NO.60	SURABAYA	-	-	-	Aktif
NA015	NATALIN / RUNGKUT	-	-	-	JL.RUNGKUT	SURABAYA	-	-	-	Aktif
TO012	TOTAL GRAFIA INDOJAYA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BE005	BERKAT	-	-	-	PS.TURI	SURABAYA	-	-	-	Aktif
HA010	HANDOKO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AD004	ADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AN015	ANEKA JAYA	-	-	-	JL.PUNGKURAN 368	SEMARANG	-	-	-	Aktif
DU009	DUTA PENA	-	-	-	PETUDUNGAN NO.24	SEMARANG	-	-	-	Aktif
SO001	SONY ST.	-	-	-	DELTASARI INDAH AV/36	SURABAYA	-	-	-	Aktif
IB002	IBU SANDRA	-	-	-	JL.NGAGEL TIRTO V/35/PDAM	SURABAYA	-	-	-	Aktif
ED001	EDISON	-	-	-	PONDOK CANDRA/NANAS 3/315	SURABAYA	-	-	-	Aktif
TR009	TRIJAYA	-	-	-	RUKO PERMATA ANCOL C/29-	30,JAKARTA UTR	-	-	-	Aktif
WA005	WAWAN AGUSTINO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AN014	ANDY TANJUNG	-	-	-	JL.PUTAT GEDE 36	SURABAYA	-	-	-	Aktif
AR002	ARTHA BARU	-	-	-	JL.	JAKARTA	-	-	-	Aktif
PU012	PUTRA UTAMA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SE026	SEKAWAN ABADI/NANA	-	-	-	JL.KARANG EMPAT NO.123	SURABAYA	-	-	-	Aktif
MU011	MUJUR STATIONERY	-	-	-	DHI BLK.UU 43 TELUK GONG	JAKARTA-UTARA	-	-	-	Aktif
MA021	MAJU JAYA	-	-	-	JL.GATOT SUBROTO 12 XX	DENPASAR - BALI	-	-	-	Aktif
SI032	SINAR SEARAH	-	-	L	JL. GUNUNGSARI 74,	DENPASAR-BALI	-	0000-00-00	-	Aktif
LA011	LAKSONO	-	-	-	PASAR PUCANG ANOM	SURABAYA	-	-	-	Aktif
PE007	PERTIWI	-	-	L	JL. MONGINSIDI 41	LAWANG	-	0000-00-00	-	Aktif
FA007	FARHAS	-	-	-	KALI RUNGKUT NO.100	SURABAYA	-	-	-	Aktif
DI002	DIA LESTARI	-	-	-	JL.A.YANI 144-B	SURABAYA	-	-	-	Aktif
SY003	SYAHBANI	-	-	-	WONOCOLO 37/PABRIK KULIT	SURABAYA	-	-	-	Aktif
MO002	MONALISA	-	-	-	PASAR PUCANG	SURABAYA	-	-	-	Aktif
GL004	GLOBUS	-	-	-	TIANG BENDERA III 54/19	JAK-BAR 11230	-	-	-	Aktif
RA014	RAHAYU	-	-	-	JL.DHOHO	KEDIRI	-	-	-	Aktif
RE008	RESTU	-	-	-	JL.BASUKI RAHMAT NO.95	TULUNGAGUNG	-	-	-	Aktif
IN005	INDOFOOD FRITOLAY	-	-	-	KETAJEN 41/JENGGOLO	GEDANGAN-SDA	-	-	-	Aktif
LA010	LANGGENG	-	-	-	JL. PRADAH PERMAI I/11	SURABAYA	-	-	-	Aktif
MI009	MINI MARKET RATNA	-	-	-	GRIYA KEBRAONUTAMA AP/9	SURABAYA	-	-	-	Aktif
CA005	CAHAYA SENTOSA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
BP002	BPK.SUPRATIK	-	-	-	JL.	MOJOSARI	-	-	-	Aktif
ME015	MENANG	-	-	-	JL.KYAI TAMIN 105H	MALANG	-	-	-	Aktif
GU009	GUNA AGUNG	-	-	-	JL.DR.SUTOMO NO.1	SINGARAJA-BALI	-	-	-	Aktif
OE002	OESAHA TAMBAH	-	-	-	JL.	SURABAYA	-	-	-	Aktif
TR008	TRISULA	-	-	-	JL.JAKSAAGUNG SUPRAPTO 23	BANYUWANGI	-	-	-	Aktif
KU006	KURNIA	-	-	-	TEMBOK DUKUH II/5 (CEPU)	SURABAYA	-	-	-	Aktif
LE002	LESTARI	-	-	-	JL.SIMPANG DUKUH NO.32	SURABAYA	-	-	-	Aktif
AM001	AMAN MAJU	-	-	-	RUNGKUT KIDUL INDUSTRY 27	SURABAYA	-	-	-	Aktif
FI002	FIRA	-	-	-	JL.PULO WONOKROMO NO.273	SURABAYA	-	-	-	Aktif
IN004	INDO JAYA	-	-	-	JL.KALI ASIN POMPA	SURABAYA	-	-	-	Aktif
SI031	SISWA	-	-	-	JL.PANGLIMA SUDIRMAN 165	TRENGGALEK	-	-	-	Aktif
NU002	NUSANTARA	-	-	-	JL.PANGLIMA SUDIRMAN 39	TRENGGALEK	-	-	-	Aktif
NA014	NAGA SAKTI	-	-	-	JL.GAJAH MADA NO.30	JEMBER	-	-	-	Aktif
SU040	SURYA STATIONERY	-	-	-	RUKO SURYA INTI P.I/B-21	SURABAYA	-	-	-	Aktif
SE025	SERBA GUNA	-	-	-	JL.SYAMANHUDI NO.48	JEMBER	-	-	-	Aktif
SA016	SARI AGUNG	-	-	-	JL.RAYA NO.184	KLAKAH	-	-	-	Aktif
SU039	SUPRIYADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
P.001	P.D.WISTA PERMAI GARSINDO	-	-	-	JL.KOMP DUTA INDAH KAPUK	BLOK B-10,JKT	-	-	-	Aktif
GE005	GEMBIRA.	-	-	-	JL.PASAR BARU NO.3	BANJARMASIN	-	-	-	Aktif
EN005	ENAM	-	-	-	JL.MERDEKA NO.156	BLITAR	-	-	-	Aktif
SE023	SENTOSA	-	-	-	JL.MAJAPAHIT NO.219	MOJOKERTO	-	-	-	Aktif
MI008	MITRA ABADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SU038	SUNDA JAYA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AP004	APAUW	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BI013	BINA MANUNGGAL WIBAWA	-	-	-	JL.TIANGBENDERA III 52/3	JAKARTA	-	-	-	Aktif
BI012	BINTANG JAYA	-	-	-	JL.GARUDA JATI NO.23	BANDUNG	-	-	-	Aktif
VE002	VEMBER/LAUTAN JAYA	-	-	-	JL.RAYA P.SUDIRMAN 269	KRAKSAN	-	-	-	Aktif
NO001	NORI CANDRA	-	-	-	JL.GATOT SUBROTO NO.287	SOLO	-	-	-	Aktif
SA015	SANTAMA JAYA	-	-	-	DHI BLK UU NO.66-68	JAKARTA	-	-	-	Aktif
AS006	ASIA	-	-	-	JL.KALIMANATAN NO.80A	JEMBER	-	-	-	Aktif
LI007	LINDA	-	-	-	JL.KRAMAT GANTUNG NO.75	SURABAYA	-	-	-	Aktif
BI011	BINTANG MAS	-	-	-	JL.STASIUN NO.34	ROGOJAMPI	-	-	-	Aktif
ME014	MEGAH MULIA	-	-	-	JL.KYAI TAMIN N0.105H	MALANG	-	-	-	Aktif
PE006	PERDANA	-	-	-	MANUKAN LOR 3L/6	SURABAYA	-	-	-	Aktif
EF002	EFRATA SWALAYAN	-	-	-	KUPANG JAYA NO.1 KAV11-12	SURABAYA	-	-	-	Aktif
MA020	MAJU	-	-	-	JL. KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
KI005	KITTO	-	-	-	MULYOSARI 87-89	SURABAYA	-	-	-	Aktif
TO011	TOKO LIE	-	-	-	PERNIAGAAN BRT III NO.11	PASAR PAGI LAMA	-	-	-	Aktif
EF001	EFENDI TJENDRAJAYA	-	-	-	JL GUNUNG KRAKATAU 102	MEDAN	-	-	-	Aktif
RE007	REMBULAN (ANAKNYA)	-	-	-	PASAR KRAMPUNG STAND B-12	SURABAYA	-	-	-	Aktif
LA009	LAIDA	-	-	-	JL.BRIGJEN KATAMSO 11	WEDORO-WARU/SDA	-	-	-	Aktif
SE022	SEJAHTERA	-	-	-	PERTOKOAN KYAI TAMIN 105E	MALANG	-	-	-	Aktif
EL003	ELSOL	-	-	-	BARATA JAYA GANG 19 NO.28	SURABAYA	-	-	-	Aktif
PU011	PUSPITA/AL-810	-	-	-	JL.	BALIKPAPAN.	-	-	-	Aktif
IK001	IKIMURA	-	-	-	JL. DR. SUTOMO 27	NGANJUK	-	-	-	Aktif
GU008	GUNUNG TIMUR	-	-	-	MANUKAN LOR 1F/12	SURABAYA	-	-	-	Aktif
TO010	TOKO BARU	-	-	-	SIMOGUNUNGKRAMAT BRT I/8A	SURABAYA	-	-	-	Aktif
SU037	SURYA MAS MANDIRI	-	-	-	KOM.RUKOHARMONIMAS C22-23	JEMBATAN II/JKT	-	-	-	Aktif
SA014	SANTO	-	-	-	JL.KALIANYAR NO.76	SURABAYA	-	-	-	Aktif
UD004	UD.ARTHA	-	-	-	JL.A.YANI NO.26	JOMBANG	-	-	-	Aktif
HA009	HADI CHANDRA	-	-	-	KREMBANGAN BARU V/20	SURABAYA	-	-	-	Aktif
TO009	TOTAL POS	-	-	-	L.RATNA 14 BLOK A NO.6	SURABAYA	-	-	-	Aktif
TE007	TENAGA BARU STATIONERY	-	-	-	DAAN MOGOTBARU BLK.LB V/3	JAKARTA	-	-	-	Aktif
TO008	TOKO JAWA TIMUR	-	-	-	JL.KEMBANG JEPUN NO.137	SURABAYA	-	-	-	Aktif
GL003	GLORY / HANDY	-	-	-	JL KALIANYAR NO.	SURABAYA	-	-	-	Aktif
AS005	ASIA RAYA PERKASA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SE021	SEJATI	-	-	-	JL.MOJOPAHIT NO.178	MOJOKERTO	-	-	-	Aktif
AC003	ACUN	-	-	-	JL.	PANGKALANBUN	-	-	-	Aktif
SU036	SURYA NAGA (ANGGIK)	-	-	-	PGS LT II BLOK E2 NO:3	SURABAYA	-	-	-	Aktif
ME013	MEKAR JAYA	-	-	-	JL.KYAI TAMIN NO.105	MALANG	-	-	-	Aktif
ST005	STATINDO KARYA PRIMA	-	-	-	DHI BLK.UU NO.66-68	JAKARTA	-	-	-	Aktif
IR001	IRIAN	-	-	-	JL.PANG.SUDIRMAN NO.130	MADIUN	-	-	-	Aktif
BE004	BERDIKARI	-	-	-	JL.DIPONEGORO NO.40	SINGARAJA-BALI	-	-	-	Aktif
SU035	SUMBER URIP	-	-	-	JL.RAYA NO.75	ROGOJAMPI	-	-	-	Aktif
F.001	F.A.GIANTO	-	-	-	JL.	PURWOKERTO	-	-	-	Aktif
DU008	DUTA PENA	-	-	-	JL.GANG PINGGIR 96-100	SEMARANG	-	-	-	Aktif
KW002	KWANG	-	-	-	PLOSO TIMUR II/4	SURABAYA	-	-	-	Aktif
UT005	UTAMA	-	-	-	JL.PIERRE TENDEAN	BANYUWANGI	-	-	-	Aktif
EL002	ELMIRA JAYA LESTARI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PU010	PUTRA JAYA	-	-	-	JL.HOES.COKROAMINOTO NO.6	JEMBER	-	-	-	Aktif
BI010	BINTANG JAYA,UD.	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
VE001	VERA	-	-	-	RAYA KUTIL 88 KEPATIHAN	MENGANTI-GRESIK	-	-	-	Aktif
UD003	UD.TUJUH-TUJUH	-	-	-	JL.WR SUPRATMAN NO.24	NEGARA/BALI	-	-	-	Aktif
UJ001	UJUNG JAYA	-	-	-	JL.PATTIMURA NO.57	SINGARAJA/BALI	-	-	-	Aktif
SU034	SUMBER JASA	-	-	-	JL.BUNG TOMO NO.12	DENPASAR/BALI	-	-	-	Aktif
IN003	INTI STATIONERY	-	-	-	JL.TEUKU UMAR 197	DENPASAR/BALI	-	-	-	Aktif
ME012	MERDEKA STATIONERY	-	-	-	SDPS V/44	SURABAYA	-	-	-	Aktif
NA013	NASIONAL	-	-	-	PERTOKOAN TOWNHOUSE B-5	SEPANJANG	-	-	-	Aktif
SU033	SUMBER HIDUP	-	-	-	JL.RAYA SOLO 19	MADIUN	-	-	-	Aktif
TR007	TRISNA JAYA	-	-	-	JL.A.YANI NO.5/SINGARAJA	BALI	-	-	-	Aktif
BE003	BERDIKARI	-	-	-	JL.PURWODADI RAYA 12	SURABAYA	-	-	-	Aktif
SU032	SUMBER MAKMUR(SUMUR DIPO)	-	-	-	JL.DIPONEGORO NO.71	PONOROGO	-	-	-	Aktif
HE007	HENDANY	-	-	-	JL.A.YANI 32	MAGETAN	-	-	-	Aktif
BA007	BALI	-	-	-	JL.PANGLIMA SUDIRMAN	MADIUN	-	-	-	Aktif
SR002	SRITI	-	-	-	JL. MOJOPAHIT	MOJOKERTO	-	-	-	Aktif
TO007	TOKO 107	-	-	L	PASAR BESAR	MALANG	-	0000-00-00	-	Aktif
LI006	LIMA EMPAT	-	-	-	JL.PETEMON	SURABAYA	-	-	-	Aktif
AH001	AHOK	-	-	-	JL.SINAR BUDI NO.45C	JAKARTA UTARA	-	-	-	Aktif
ME011	MEKAR TERUS	-	-	-	PSR TURI LT.I H8(KTSI UTR	GG.II/11) SBY	-	-	-	Aktif
SU031	SUMBER BARU	-	-	-	PASAR TURI	SURABAYA	-	-	-	Aktif
AC002	ACC SABLON	-	-	-	KOMPLEK PJKA NO.96	PURWOKERTO	-	-	-	Aktif
WI004	WILLY	-	-	-	JL.PAKIS TIRTOSARI V/56	SURABAYA	-	-	-	Aktif
RO003	ROY	-	-	-	ABIMANYU 9 BANJARMANTRI	CAKRANEGARA-LMB	-	-	-	Aktif
LA008	LANCAR	-	-	-	JL.NIAGA UTARA A 22-23	SAMARINDA	-	-	-	Aktif
A 003	A LUNG	-	-	-	JL.	SBY	-	-	-	Aktif
MU010	MUTIARA	-	-	-	BABADAN MUKTI 6/E-44	SBY	-	-	-	Aktif
TR006	TRIJAYA	-	-	-	CIBADAK 97	BANDUNG	-	-	-	Aktif
NU001	NUSANTARA	-	-	-	KERTAJAYA VII RAYA NO.8	SURABAYA	-	-	-	Aktif
AS004	ASIEN	-	-	-	RUKO MANGGA DUA	SURABAYA	-	-	-	Aktif
AN013	ANEKA VITA	-	-	-	JL.PANGLIMA SUDIRMAN 28	LUMAJANG	-	-	-	Aktif
TO006	TOKO BUKU BANYU MAS	-	-	-	PINTUKELUAR STASIUNWKROMO	SURABAYA	-	-	-	Aktif
SU030	SUKSES	-	-	-	PS.PUCANG ANOM NO.141	SURABAYA	-	-	-	Aktif
IB001	IBU ANIS	-	-	-	PETEMON III/122B	SURABAYA	-	-	-	Aktif
KU005	KURNIA JAYA	-	-	-	KAPAS KRAMPUNG NO.158	SURABAYA	-	-	-	Aktif
AG003	AGUNG	-	-	-	JL.JEND.SUDIRMAN NO.50	PONOROGO	-	-	-	Aktif
GU007	GUNUNG MAS	-	-	-	JL.HAJI AGUSSALIM NO.155	MADIUN	-	-	-	Aktif
MA019	MARIA	-	-	-	JL.JEND.A.YANI NO.143	MADIUN	-	-	-	Aktif
PR003	TK PRIMA	-	-	-	JL.KH AGUS SALIM NO.141	MADIUN	-	-	-	Aktif
SI030	SISWA BARU	-	-	-	JL.TEUKU UMAR NO.63	TULUNG AGUNG	-	-	-	Aktif
SE020	SEMPURNA	-	-	-	JL.	MOJOKERTO	-	-	-	Aktif
TR005	TRISAKTI	-	-	-	JL.BRAWIJAYA	KEDIRI	-	-	-	Aktif
SE019	SEMBILAN	-	-	-	JL.DHOHO NO.11	KEDIRI	-	-	-	Aktif
KO005	KO AN / YURIKO	-	-	-	JL.KAPAS KRAMPUNG	SURABAYA	-	-	-	Aktif
BI009	BINAWATI	-	-	-	KLAMPISANOM VI/5 BLK F-96	SURABAYA	-	-	-	Aktif
KU004	KUSNO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BO005	BOROBUDUR	-	-	-	JL.PUSPOMJOLO BARAT NO.26	SEMARANG	-	-	-	Aktif
GU006	GUNINDO UTAMA PERKASA IND	-	-	-	JL.PETOJO UTARA I/12B	JAKARTA	-	-	-	Aktif
TO005	TOKO SISWA	-	-	-	JL.TEUKU UMAR NO 15	PROBOLINGGO	-	-	-	Aktif
A.001	A.A	-	-	-	BENDUL MERISI NO.169	SURABAYA	-	-	-	Aktif
ME010	MEGA SAKTI	-	-	-	JL.KOMPLEK DHI BLOK KK 16	JAKARTA	-	-	-	Aktif
MU009	MUDA JAYA	-	-	-	JL.KH.AHMAD DAHLAN	PURWOREJO	-	-	-	Aktif
MA018	MARTIN	-	-	-	JL.KALIMALANG 11B	SURABAYA	-	-	-	Aktif
DA003	DARTO	-	-	-	KALILOMLOR BARU III/14	SURABAYA	-	-	-	Aktif
AL005	ALVIN W.	-	-	-	JL. KENJERAN 516 KAV.24	SURABAYA	-	-	-	Aktif
WS001	WS-SMG	-	-	-	JL.	SEMARANG	-	-	-	Aktif
MM001	MM 68	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
BH002	BH 233	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
UD002	UD.NSD	-	-	-	GNG.AGUNG BULUH.INDV111/2	DENPASAR/BALI	-	-	-	Aktif
NA012	NADHI (MERTAYASA)	-	-	L	JL.MERTAYASA NO.12	DENPASAR/BALI	-	0000-00-00	-	Aktif
AS003	ASIA	-	-	-	JL.VETERAN NO.25	DENPASAR/BALI	-	-	-	Aktif
GE004	GEMBIRA	-	-	-	BARAT PASAR NO.2 GIANYAR	BALI	-	-	-	Aktif
ME009	MENARA	-	-	-	JL.NGURAH RAI 24-A	NEGARA/BALI	-	-	-	Aktif
S.001	S.B.R.	-	-	-	JL.KH WAHID HASYIM 113	PASURUAN	-	-	-	Aktif
DE006	DENPASAR INDAH	-	-	L	BULUK IND JL.CEMPAKA BIRU	II/2 DENPASAR	-	0000-00-00	-	Aktif
RI004	RIANG	-	-	-	JL.DIPONEGORO N0.3	KLUNGKUNG/BALI	-	-	-	Aktif
TR004	TRD/NO.89	-	-	-	SIMPANGELTARIWJLALAMENTIK	KUPANG/NTT	-	-	-	Aktif
LO002	LOTTO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
DK001	DK-68	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
CA004	CAHAYA	-	-	-	JL.SONGOYUDAN NO.100	SURABAYA	-	-	-	Aktif
GU005	GUNUNG SARI JAYA	-	-	-	JL.KEMBANG JEPUN NO.141	SURABAYA	-	-	-	Aktif
SE018	SEAN YOUNG/SUMBER KARUNIA	-	-	-	JL. KAPASARI	SURABAYA	-	-	-	Aktif
GL002	GLOBAL	-	-	-	DARMAHUSADA IND UT.VI/47	SURABAYA	-	-	-	Aktif
FA006	FAJAR STATIONERY	-	-	-	BRATANG GEDE G VI/52	SURABAYA	-	-	-	Aktif
SE017	SERBA JAYA / SIDARTA	-	-	-	RUNGKUTMAPAN BRT IV/BD-16	SURABAYA	-	-	-	Aktif
LI005	LIMA JAYA ABADI	-	-	-	JL	JAKARTA	-	-	-	Aktif
UN002	UNGGUL JAYA	-	-	-	SEMOLOWARUJAYA BLOK AB/12	SURABAYA	-	-	-	Aktif
AC001	ACE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
NI003	NIKIMURA	-	-	-	PS.TURI LT.1-G NO.27-28	SURABAYA	-	-	-	Aktif
HA008	HADI SUHARDJO	-	-	-	JL.	JAKARTA	-	-	-	Aktif
FE002	FERRY	-	-	-	KUTISARINDAH UTARA III/46	SURABAYA	-	-	-	Aktif
SE016	SEKAWAN JAYA	-	-	-	PGS. LT.1 E7 NO.23	SURABAYA	-	-	-	Aktif
CI006	CIE HOO	-	-	-	JL.PLOSO TIMUR V/55	SURABAYA	-	-	-	Aktif
AD003	ADISAN JAYA PERKASA	-	-	-	JL.DARMAWANGSA NO.42C	SURABAYA	-	-	-	Aktif
NA011	NASIONAL	-	-	-	JL.KYAI TAMIN NO.57	MALANG	-	-	-	Aktif
BU009	BUDIMAN ARIF/MINOLTA	-	-	-	JL.HARYONO MT.NO.30/69	BANJARMASIN	-	-	-	Aktif
OS001	OSKAR.UD	-	-	-	JL.SIMPANGDARMO PS IV/37	SURABAYA	-	-	-	Aktif
AN012	ANEKA KARYA	-	-	-	JL.MARGOREJO INDAH 28E	SURABAYA	-	-	-	Aktif
BP001	BPK.EDY	-	-	-	JL.JEMURSARI III/63	SURABAYA	-	-	-	Aktif
AB004	ABC	-	-	-	JL.TRUNOJOYO NO.79	PAMEKASAN	-	-	-	Aktif
PU009	PUTRA SURYA MANDIRI	-	-	-	KOMP.DHI BLOK UU NO.60	JAKARTA	-	-	-	Aktif
DE005	DEWATA ELECTRIK	-	-	-	JL.PALEM II/TE NO.39	SURABAYA	-	-	-	Aktif
GU004	GUNTORO	-	-	-	JL.EMBONG SAWO NO.40	SURABAYA	-	-	-	Aktif
MI007	MIG	-	-	-	JL.KEMBANGJEPUN NO.129/5	SURABAYA	-	-	-	Aktif
SU029	SUPRATIK	-	-	-	JL.HAYAM WURUK NO.28	MOJOSARI/SBY	-	-	-	Aktif
MU008	MUDA JAYA	-	-	-	PURWOREJO	JAWA - TENGAH	-	-	-	Aktif
SY002	SYLVIA	-	-	-	JL.PUCANG ADI NO.09	SURABAYA	-	-	-	Aktif
TK001	TK.SEMBILAN BELAS	-	-	-	JL.DUPAK/DUPAKMEGA B-25	SURABAYA	-	-	-	Aktif
AN011	ANDA	-	-	-	JL.TRUNOJOYO NO.24	SUMENEP	-	-	-	Aktif
GR004	GRAFIKA ASRI	-	-	-	JL.TRUNOJOYO	PAMEKASAN	-	-	-	Aktif
SA013	SARANA KRAFTINDO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SI029	SINAR ABADI	-	-	-	PS.PUCANG ANOM NO.143	SURABAYA	-	-	-	Aktif
T.001	T.K.	-	-	-	SURABAYA	-	-	-	-	Aktif
PT002	PT.AJBS	-	-	-	JL.SEMARANG 116D-E	SURABAYA	-	-	-	Aktif
KH001	KHARISMA	-	-	-	JL.GUBENG KLINGSINGAN 46	SURABAYA	-	-	-	Aktif
WA004	WARNA CITRA MANDIRI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
VA002	VARIA (FERRY)	-	-	-	JL.MANYAR TIRTOASRI III/4	SURABAYA	-	-	-	Aktif
TU004	TUJUH SEMBILAN	-	-	-	JL.TRUNOJOYO NO.77	PAMEKASAN	-	-	-	Aktif
SI028	SINAR SURYA INDAH SENTOSA	-	-	-	JL.MARGO MULYO 44C-9	SURABAYA	-	-	-	Aktif
WA003	WARAS	-	-	-	JL.SIMOMARGEREJO IX NO.01	SURABAYA	-	-	-	Aktif
HA007	HARIN INTERNUSA PT.	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BU008	BUDIMAN	-	-	-	JL.	BANJARMASIN	-	-	-	Aktif
AL004	AL-810 /PUSPITA	-	-	-	JL.	BALIK - PAPAN	-	-	-	Aktif
SI027	SINAR JAYA	-	-	-	NGAGEL JAYA UTARA N0.90	SURABAYA	-	-	-	Aktif
KE002	KELAPA MAS	-	-	-	MANGGA DUA B6 NO.07	SURABAYA	-	-	-	Aktif
MU007	MUSTIKA	-	-	-	KAPAS RAYA UTARA G/926.B	SEMARANG	-	-	-	Aktif
KU003	KURNIA ABADI	-	-	-	JL.KESEHATAN NO.08	PAMEKASAN	-	-	-	Aktif
KA009	KARUNIA	-	-	-	MANUKAN DALAM 18F NO.11	SURABAYA	-	-	-	Aktif
WI003	WIJAYA SANTOSO	-	-	-	JL.SONGOYUDAN NO.51	SURABAYA	-	-	-	Aktif
KO004	KOPERASI BINA MAJU	-	-	-	JL.	SURABAYA	-	-	-	Aktif
LI004	LILY	-	-	-	LAWANG SEKETENG III/21	SURABAYA	-	-	-	Aktif
PU008	PUTRA HARAPAN SUKSES	-	-	-	KAPUKMUARA DHI BLK.TT/68	JAKARTA-UTARA	-	-	-	Aktif
PR002	PRIBADI	-	-	-	JL.MANYAR JAYA XI/11	SURABAYA	-	-	-	Aktif
KA008	KALDYA PRINT	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AN010	ANUGERAH	-	-	-	JL.DIPONEGORO NO.85	SIDOARJO	-	-	-	Aktif
LE001	LESTARI	-	-	-	JL.INDUSTRI XX / 790	SEMARANG	-	-	-	Aktif
SU028	SUPER	-	-	-	PASAR TURI	SURABAYA	-	-	-	Aktif
AN009	ANEKA JAYA	-	-	-	PASAR TURI LT.1E NO.107	SURABAYA	-	-	-	Aktif
CI005	CITRA MANDIRI	-	-	-	JL.INDRAPURA NO.34	SURABAYA	-	-	-	Aktif
MI006	MING	-	-	-	JL.KLENTENG GG.BUDIMAN/07	BANDUNG	-	-	-	Aktif
MA017	MARIA	-	-	-	JL.JUWET NO.27	SURABAYA	-	-	-	Aktif
SI026	SINAR ABADI	-	-	-	KOMPLEK.DHI BLK.II NO:32	JAKARTA	-	-	-	Aktif
BU007	BUMI PUTRA	-	-	-	JL.KAUMAN	SOLO	-	-	-	Aktif
EK002	EKA JAYA	-	-	-	JL.DARMA HUSADA 38 B	SURABAYA	-	-	-	Aktif
PA002	PALAPA	-	-	-	JL.ADITYAWARMAN NO.41A	SURABAYA	-	-	-	Aktif
DO002	DONNY	-	-	-	PULO WONOKROMO NO.30A	SURABAYA	-	-	-	Aktif
MA016	MATAHARI	-	-	-	JL.KALIBUTUH NO.107	SURABAYA	-	-	-	Aktif
NY002	NY.ARIF	-	-	-	RUNGKUT MAPANTIMUR I/EA/4	SURABAYA	-	-	-	Aktif
CI004	CITRA BUNDA (IBU LIS)	-	-	-	JL.KUSUMA BANGSA N0.32	SURABAYA	-	-	-	Aktif
BA006	BAJA TEKHNIK MCH	-	-	-	JL.DUPAK NO.79	SURABAYA	-	-	-	Aktif
BA005	BANYUWANGI	-	-	-	VILA KALIJUDAN BLK.J/09	SURABAYA	-	-	-	Aktif
AN008	ANDA	-	-	-	JL.KALI RUNGKUT 130 B	SURABAYA	-	-	-	Aktif
ER001	ERA TIRTA JAYA (ETJ)	-	-	-	TAMAN DUTA MAS BLK.C IC/1	JAKARTA	-	-	-	Aktif
RE006	REMAJA MINI MARKET	-	-	-	JL.KUTAI NO.70 A	SURABAYA	-	-	-	Aktif
SE015	SETIA MAKMUR	-	-	-	DARMO PERMAI SELATAN 5/52	SURABAYA	-	-	-	Aktif
MU006	MUTIARA	-	-	-	DARMO PERMAI SELATAN 5/50	SURABAYA	-	-	-	Aktif
SE014	SETIA JAYA	-	-	-	PS.TURI / KUPANG JAYA 130	SURABAYA	-	-	-	Aktif
RA013	RAMAYANA	-	-	-	PS.KEDUNGDORO 58 - 60	SURABAYA	-	-	-	Aktif
KI004	KIAN PING	-	-	-	SUTOREJOTENGAH XI/10 DD30	SURABAYA	-	-	-	Aktif
TE006	TERUS MAKMUR BERSAMA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
ME007	MEGA MAS	-	-	-	JL.BANDENGAN UTARA 83/14	JAKARTA UTARA	-	-	-	Aktif
SU027	SURYA	-	-	-	JL.PALEM I/TC4 PND.CANDRA	SURABAYA	-	-	-	Aktif
C.001	C.V  A.P.I	-	-	-	JL.MARGOMULYO INDAH I	BLOK F-35,SBY	-	-	-	Aktif
PO001	POLLY	-	-	-	JL.PASAR PAGI RAYA N0.109	JAKARTA	-	-	-	Aktif
EN003	ENDANG	-	-	-	PASAR PUCANG ANOM	SURABAYA	-	-	-	Aktif
BU006	BUMI AYU	-	-	-	JL.PUCANG ANOM N0.11	SURABAYA	-	-	-	Aktif
EK001	EKA JAYA	-	-	-	JL.GUBENG MASJID N0.65	SURABAYA	-	-	-	Aktif
RA012	RAPI INDAH	-	-	-	JL.PASAR KEMBANG 87A	SURABAYA	-	-	-	Aktif
SI025	SINAR SURYA	-	-	-	JL.TEMPEL SUKOREJO I/50	SURABAYA	-	-	-	Aktif
DE004	DELIMA	-	-	-	JL.PETEMON KALI N0.05	SURABAYA	-	-	-	Aktif
SE013	SEKAWAN	-	-	-	PASAR TURI BLK H19 LT.DSR	SURABAYA	-	-	-	Aktif
SE012	SEMI	-	-	-	JL.BASUKI RAHMAT NO.38	SURABAYA	-	-	-	Aktif
NA010	NASIONAL	-	-	-	JL.PACARKELING NO.35	SURABAYA	-	-	-	Aktif
TA006	TANAKURA	-	-	-	JL.KARANG MENJANAGAN 34 A	SURABAYA	-	-	-	Aktif
XE001	XEROX	-	-	-	JL.KARANG MENJANGAN 34 A	SURABAYA	-	-	-	Aktif
RA011	RATNA TOSERBA	-	-	-	JL.KEDUNG COWEK NO.66	SURABAYA	-	-	-	Aktif
PE005	PETEMON BARAT	-	-	-	JL.PETEMON BARAT 54	SURABAYA	-	-	-	Aktif
LA007	LANCAR	-	-	-	TAMBAK SEGARAN NO.19	SURABAYA	-	-	-	Aktif
TE005	TEGUH	-	-	-	JL.KARANGEMPAT BESAR 42	SURABAYA	-	-	-	Aktif
TR003	TRIO	-	-	-	JL.PANGLIMA SUDIRMAN 104	LUMAJANG	-	-	-	Aktif
PU007	PUSPA INDAH	-	-	-	JL.KENJERAN 406	SURABAYA	-	-	-	Aktif
DE003	DELAPAN SATU	-	-	-	JL.KARANG ASEM 4/81	SURABAYA	-	-	-	Aktif
MA015	MAHKOTA	-	-	-	JL.KALIBUTUH NO.107	SURABAYA	-	-	-	Aktif
RU002	RUNGKUT JAYA	-	-	-	RUNGKUT KIDUL 44-50	SURABAYA	-	-	-	Aktif
AT001	ATET	-	-	-	KRUKAH UTARA NO.58	SURABAYA	-	-	-	Aktif
SI024	SINAR JAYA	-	-	-	JL.RAJAWALI N0.105	SURABAYA	-	-	-	Aktif
KI003	KIKY	-	-	-	JL.PANDEGILING N0.31	SURABAYA	-	-	-	Aktif
IN002	INDAH JAYA	-	-	-	JL.KEPANJEN NO.16	SURABAYA	-	-	-	Aktif
JA007	JAYA RAYA (BJM)	-	-	-	JL.PS.BARU NO.80	BANJARMASIN	-	-	-	Aktif
WI002	WIJAYA	-	-	-	JL.DUKUH KUPANG XX/38	SURABAYA	-	-	-	Aktif
RA010	RAYA	-	-	-	JL.DUKUH KUPANG NO.46	SURABAYA	-	-	-	Aktif
CA003	CAHAYA MINI MARKET	-	-	-	JL.DUKUH KUPANG 20/16	SURABAYA	-	-	-	Aktif
TO004	TOSERBA PRAWIRA	-	-	-	JL.BENDUL MERISI NO.06	SURABAYA	-	-	-	Aktif
SE011	SEJATI	-	-	-	JL.PETEMON KALI NO.87	SURABAYA	-	-	-	Aktif
SU026	SULING MAS	-	-	-	PASAR PUCANG ANOM AA-3/4	SURABAYA	-	-	-	Aktif
IM002	IMMANUEL PUCANG	-	-	-	JL.PS PUCANG ANOM BL-128	SURABAYA	-	-	-	Aktif
SU025	SUMBER JAYA	-	-	-	JL.JOJORAN I/2	SURABAYA	-	-	-	Aktif
DU007	DUA ENAM	-	-	-	JL.DARMAWANGSA NO.26	SURABAYA	-	-	-	Aktif
LA006	LARIS JAYA	-	-	-	JL.KALIANYAR NO.70	SURABAYA	-	-	-	Aktif
ME006	MEGA STATIONERY	-	-	-	JL.	JAKARTA	-	-	-	Aktif
FA005	FAVORIT	-	-	-	JL.KRAMAT GANTUNG NO.152	SURABAYA	-	-	-	Aktif
NA009	NAGA JAYA	-	-	-	JL.SIDOLUHUR NO.05	SURABAYA	-	-	-	Aktif
HA006	HASIL	-	-	-	JL.SIDOLUHUR NO.04	SURABAYA	-	-	-	Aktif
SU024	SUMBER JAYA	-	-	-	JL.KREMBANGAN BARU NO.8	SURABAYA	-	-	-	Aktif
TA005	TABAH JAYA	-	-	-	JL. PANDEGILING NO.23	SURABAYA	-	-	-	Aktif
KU002	KURNIA	-	-	-	JL.JAGARAGA NO.15	SURABAYA	-	-	-	Aktif
RE005	REJEKI	-	-	-	JL.KALI BUTUH NO.63	SURABAYA	-	-	-	Aktif
UT004	UTAMA	-	-	-	JL.TIDAR NO.138	SURABAYA	-	-	-	Aktif
BO004	BOK ABANG	-	-	-	JL.BANYU URIP NO.170	SURABAYA	-	-	-	Aktif
BU005	BU SITI	-	-	-	JL.KETINTANG NO.125	SURABAYA	-	-	-	Aktif
AR001	ARISON	-	-	-	JL.MANYAR TIRTOMOYO NO.40	SURABAYA	-	-	-	Aktif
SI023	SINAR HARAPAN	-	-	-	JL.KEDUNGDORO NO.61	SURABAYA	-	-	-	Aktif
SU023	SUMBER TIDAR AGUNG	-	-	-	JL.TIDAR NO.4-8	SURABAYA	-	-	-	Aktif
YO001	YOPIE WIJAYA	-	-	-	JL.SUTOREJO TIMUR VI/15	SURABAYA	-	-	-	Aktif
TR002	TRININDA	-	-	-	JL.SUPRIADI NO.193	SEMARANG	-	-	-	Aktif
MI005	MICHAEL	-	-	-	ANJASMORO27 WISMA TROPODO	WARU SIDOARJO	-	-	-	Aktif
ME005	MEDIA	-	-	-	JL.DARMAWANGSA NO.47	SURABAYA	-	-	-	Aktif
DU006	DUTA INDAH SWALAYAN	-	-	-	PACAR KELING NO.12	SURABAYA	-	-	-	Aktif
MU005	MULIA MINI MARKET	-	-	-	KAPAS KRAMPUNG 118A	SURABAYA	-	-	-	Aktif
PE004	PERKASA JAYA	-	-	-	JL. KALIANYAR NO.68 A-B	SURABAYA	-	-	-	Aktif
BH001	BHAKTI	-	-	-	JL. RAJAWALI NO.101	SURABAYA	-	-	-	Aktif
GL001	GLORY/YUDI	-	-	-	JL.PS BLAURAN,	SURABAYA	-	-	-	Aktif
KU001	KUTAI	-	-	-	JL. KUTAI NO.56-58	SURABAYA	-	-	-	Aktif
SE010	SEPULUH	-	-	-	DARMO BARU BARAT IV/10	SURABAYA	-	-	-	Aktif
AN007	ANUGRAH	-	-	-	JL.GEMBONG SAWAH N0.1	SURABAYA	-	-	-	Aktif
KA007	KARTIKA	-	-	-	JL. KALISOSOK NO.15	SURABAYA	-	-	-	Aktif
KA006	KARINA	-	-	-	BENDUL MERISI NO.142-144	SURABAYA	-	-	-	Aktif
RE004	REJEKI	-	-	-	BENDUL MERISI PERMAI I/2	SURABAYA	-	-	-	Aktif
GE003	GEMINI	-	-	-	JL.MANYAR NO.8	SURABAYA	-	-	-	Aktif
TA004	TANJUNG	-	-	-	JL. KALIBUTUH NO.61	SURABAYA	-	-	-	Aktif
BR001	BROMO PLAZA	-	-	-	JL.BROMO NO.21	SURABAYA	-	-	-	Aktif
SU022	SUBUR FOTO	-	-	-	PETEMON KALI NO.29	SURABAYA	-	-	-	Aktif
SU021	SURYA	-	-	-	RUNGKUT MENANGGAL SEL Q2	SURABAYA	-	-	-	Aktif
CI003	CIPTA KARYA	-	-	-	JL.NGAGEL JAYA SEL NO.47	SURABAYA	-	-	-	Aktif
CV001	CV.SINAR TERANG	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SR001	SRI GADING	-	-	-	JL. PUCANG SEWU NO.38	SURABAYA	-	-	-	Aktif
RA009	RAME	-	-	-	JL. KALIBOKOR SELATAN 14	SURABAYA	-	-	-	Aktif
AN006	ANDHIKA JAYA	-	-	-	JL.PACAR KELING NO.6	SURABAYA	-	-	-	Aktif
PE003	PELANGI	-	-	-	JL.TENGGILIS NO.137	SURABAYA	-	-	-	Aktif
SU020	SUMBER REJEKI	-	-	-	KARANG EMPAT BESAR NO.5	SURABAYA	-	-	-	Aktif
SA012	SAHABAT BARU	-	-	-	KARANG EMPAT BESAR 109	SURABAYA	-	-	-	Aktif
SU019	SURYA	-	-	-	JL.NGAGLIK 28	SURABAYA	-	-	-	Aktif
SL001	SLAMET	-	-	-	JL.LEBAK ARUM 4/6	SURABAYA	-	-	-	Aktif
AB003	ABC MINI MARKET	-	-	-	JL. KUSUMA BANGSA NO.59	SURABAYA	-	-	-	Aktif
ME004	MELATI SWALAYAN	-	-	-	JL. PERAK TIMUR NO.164	SURABAYA	-	-	-	Aktif
KA005	KARUNIA	-	-	-	JL. PASAR BARU LAMONGAN	LAMONGAN	-	-	-	Aktif
SU018	SUBUR JAYA	-	-	-	JL. SIDODADI BARU NO.16	SURABAYA	-	-	-	Aktif
EM001	EMPAT LIMA	-	-	-	JL. JAKARTA NO.45	SURABAYA	-	-	-	Aktif
KO003	KOH EFENDY (OPTIK 2000)	-	-	-	JL. G.KRAKATAU NO.102	MEDAN	-	-	-	Aktif
SU017	SUMBER REJEKI	-	-	-	JL.SAMPURNA NO.28	SURABAYA	-	-	-	Aktif
SU016	SUMBER JAYA	-	-	-	JL. JAKARTA NO.26	SURABAYA	-	-	-	Aktif
MU004	MUDA KURNIA	-	-	-	JL.KERAPU NO.7	SURABAYA	-	-	-	Aktif
RA008	RATNA WIJAYA	-	-	-	JL. TELUK NIBUNG 8	SURABAYA	-	-	-	Aktif
UT003	UTAMA	-	-	-	JL. IKAN DUYUNG 2 A	SURABAYA	-	-	-	Aktif
DA002	DAYA BARU	-	-	-	JL.	MAKASAR	-	-	-	Aktif
SU015	SURYA MIE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
PU006	PULO MAS	-	-	-	JL. SANGGAR 51	SURABAYA	-	-	-	Aktif
KA004	KARUNIA TURI	-	-	-	DUPAK MEGAH A-7	SURABAYA	-	-	-	Aktif
TO003	TOMY HOO	-	-	-	JL.THAMRIN NO.60	SEMARANG	-	-	-	Aktif
LA005	LARIS	-	-	-	JL.KH. WAKHID HASIM 153	SAMPANG	-	-	-	Aktif
BM005	BMW PALEMBANG	-	-	-	JL.KOLONEL ATMO 437 C / 3	PALEMBANG	-	-	-	Aktif
TO002	TOKYA	-	-	-	PS.ATOM THP II LT 1 1080B	SURABAYA	-	-	-	Aktif
HR001	HR.SURYA AGUNG	-	-	-	JL.	SURABAYA	-	-	-	Aktif
SE009	SEHATI	-	-	-	JL.MALAKA 11 NO.34 BB	JAKARTA	-	-	-	Aktif
MA014	MARCONATA	-	-	-	JL.PASAR PAGI LAMA 112	JAKARTA	-	-	-	Aktif
MA013	MAKIN MAKMUR	-	-	-	JL. KALI ANYAR NO. 76	SURABAYA	-	-	-	Aktif
WA002	WAHONO	-	-	-	PUNTEN NO.27 KEPANJEN	MALANG	-	-	-	Aktif
ST004	STELY / TIGA PRIMA	-	-	-	NGAGEL JAYA INDAH 15	SURABAYA	-	-	-	Aktif
SU014	SUTIKNO	-	-	-	LEBAK INDAH UTR 5/50	SURABAYA	-	-	-	Aktif
YU002	YU HAW	-	-	-	JL.KARANG ASEM IV/38	SURABAYA	-	-	-	Aktif
BU004	BUDI	-	-	-	RUNGKUT ASRI BARAT XIV/9	SURABAYA	-	-	-	Aktif
CI002	CIPTA INDAH / LYDIA	-	-	-	JL. GERSIKAN NO. 22	SURABAYA	-	-	-	Aktif
AV001	AVIC PT.	-	-	-	JL.MALAKA NO.24A	JAKARTA BARAT	-	-	-	Aktif
GU003	GUNAWAN	-	-	-	JL.VETERAN	BANJARMASIN	-	-	-	Aktif
LO001	PT LOCOMOTIF EKA SAKTI	-	-	-	-	JKT	-	-	-	Aktif
PU005	PUTRA MAHKOTA	-	-	-	MUARA KARANG BLK DVII BRT	JAKARTA	-	-	-	Aktif
BA004	BANGKIT	-	-	-	JL.BANDENGAN UTARA 36-B	JAKARTA UTARA	-	-	-	Aktif
NA008	NAPINDO II PT.	-	-	-	JL.DONOREJO WETAN 54B	SURABAYA	-	-	-	Aktif
BU003	BUDI STATIONERY	-	-	-	JL.JEMBATAN TIGA 38	JAKARTA	-	-	-	Aktif
BA003	BANYU URIP PASARAYA	-	-	-	JL.BANYU URIP 176-178	SURABAYA	-	-	-	Aktif
GE002	GEDANGAN JAYA ABADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
UN001	UNTUNG JAYA	-	-	-	JL.SMEA NO.9A	SURABAYA	-	-	-	Aktif
SE008	SENTRAL DHARMA PERKASA	-	-	-	AM.SANGAJI 10D(G SADAR)II	JAKARTA	-	-	-	Aktif
SI022	SISWA	-	-	-	JL.	MALANG	-	-	-	Aktif
AK001	AKRAB	-	-	-	JL.BANYU URIP	SURABAYA	-	-	-	Aktif
SU013	SUKSES ABADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BE002	BERKAT	-	-	-	JL.PANDEGILING 167 C	SURABAYA	-	-	-	Aktif
HO001	HOK AN	-	-	-	JL.KALIASIN 11/6	SURABAYA	-	-	-	Aktif
IJ001	IJO	-	-	-	JL.	MALANG	-	-	-	Aktif
AF001	AFINDO/MARTIN	-	-	-	PROYEK PERNIAGAAN BLK B52	JAKARTA BARAT	-	-	-	Aktif
SI021	SINAR BUANA LESTARI	-	-	-	JL.KEBON KANGKUNG 182/88	BANDUNG	-	-	-	Aktif
SE007	SEPAKAT	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
HE006	HERY	-	-	-	K.S TUBUN GG.II DAMAI NO.	4 RT 28 B/SIN	-	-	-	Aktif
DO001	DOA RESTU	-	-	-	KOMP.DUTA HRP INDAH H/6	JAKARTA	-	-	-	Aktif
AY001	AYU MAS	-	-	-	JAKSA AGUNG SUPRAPTO 59	MALANG	-	-	-	Aktif
BU002	BUKIT PERMAI	-	-	-	PS.INDUK CARINGIN BLOK A2	BANDUNG	-	-	-	Aktif
MA012	MAKMUR UD	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SA011	SATU	-	-	-	JL.DHOHO 145-149	KEDIRI	-	-	-	Aktif
SU012	SURIN JAYA	-	-	-	JL.MANGGA DUA RAYA	JAKARTA	-	-	-	Aktif
GR003	GRAMEDIA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
IN001	INDOMAS STATIONERY / IMS	-	-	-	TAMAN SARI IV NO:6A	JAKARTA	-	-	-	Aktif
HA005	HASIL KARYA	-	-	-	JL.JEND.GATOT SUBROTO 23	SOLO	-	-	-	Aktif
NI002	NIEN FAT	-	-	-	JL.KARANG EMPAT,	SURABAYA.	-	-	-	Aktif
SA010	SAKTI/AFAT	-	-	-	JL.SUTOREJO TENGAH XIII/6	SURABAYA	-	-	-	Aktif
GR002	GRAMEDIA	-	-	-	JL.	DILI	-	-	-	Aktif
AN005	ANUGRAH CIPTA ABADI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SI020	SINAR LAUT	-	-	-	JL.PANGGUNG	SURABAYA	-	-	-	Aktif
MA011	MATAHARI	-	-	-	JL. PANGGUNG	SURABAYA	-	-	-	Aktif
MI004	MITRA UTAMA UD	-	-	-	JL.DINOYO NO.110	SURABAYA	-	-	-	Aktif
PE002	PENGAMPON	-	-	-	JL.PENGAMPON NO.11	SURABAYA	-	-	-	Aktif
RA007	RAHAYU	-	-	-	JAGIR WONOKROMO WETAN 14	SURABAYA	-	-	-	Aktif
PT001	PT.GADING MURNI	-	-	-	JL.TUNJUNGAN 27	SURABAYA	-	-	-	Aktif
MA010	MARTIN/A CIEN	-	-	-	PLUIT MAS BLOK 5D NO.10A	JAKARTA UTARA	-	-	-	Aktif
RI003	RIAN	-	-	-	P.TURI LT.DSR D1 NO.1-2-8	SURABAYA	-	-	-	Aktif
SH002	SHOLEH	-	-	-	JL.SIDONIPAH 37	SURABAYA	-	-	-	Aktif
MA009	MAKIN MAKMUR	-	-	-	JL.INDUSTRI RAYA BRT NO,2	SEMARANG	-	-	-	Aktif
BI008	BIMAS	-	-	-	JL.KARANG MULIA	JAKARTA BARAT	-	-	-	Aktif
HE005	HENDRY	-	-	-	JL.SIMOLAWANG BARU IV/30	SURABAYA	-	-	-	Aktif
GR001	GRAMEDIA	-	-	-	JL.	UJUNG PANDANG	-	-	-	Aktif
CI001	CIN PAU	-	-	-	JL.TPI II BLOK M-I/08	JAKARTA UTARA	-	-	-	Aktif
DF001	DFR(RSL)	-	-	-	RANTAUAN TIMUR I/2 RT.23	BANJARMASIN	-	-	-	Aktif
RI002	RINI	-	-	-	JL.PUCANG ANOM TIMUR 8B	SURABAYA	-	-	-	Aktif
WA001	WANGSA	-	-	-	JL.MANYAR KERTOARJO XI/15	SURABAYA	-	-	-	Aktif
SA009	SAHABAT BARU	-	-	-	JL. DHOHO 91,	KEDIRI	-	-	-	Aktif
FO003	FOTO CITRA	-	-	-	JL.RAYA PAGESANGAN 27	SURABAYA	-	-	-	Aktif
FI001	FILIA CRISTY	-	-	-	JL.KARANG ASEM VI/04	SURABAYA	-	-	-	Aktif
SU011	SURYA	-	-	-	JL.KAPASAN 37	SURABAYA	-	-	-	Aktif
DI001	DINGDING	-	-	-	JL.KEPATIHAN IX/08	SURABAYA	-	-	-	Aktif
PE001	PETEMON SWALAYAN	-	-	-	JL.PETEMON III/132	SURABAYA	-	-	-	Aktif
PI003	PING LIE	-	-	-	JL. R.K ILIR 509,	BANJARMASIN	-	-	-	Aktif
SA008	SARI AGUNG	-	-	-	JL.TUNJUNGAN NO.05	SURABAYA	-	-	-	Aktif
SA007	SALISUGIH	-	-	-	JL.SONGOYUDAN NO.24	SURABAYA	-	-	-	Aktif
JA006	JAWA INDAH	-	-	-	JMP LT.DASAR BLOK	SURABAYA	-	-	-	Aktif
NA006	NAGA MAS BARU	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
TA003	TABAH	-	-	-	JL.NGAGEL JAYA SELATAN 45	SURABAYA	-	-	-	Aktif
UT002	UTAMA PERKASA INDUSTRIES	-	-	-	TSS RAYA 20Q JEMB.LIMA	JAKARTA BARAT	-	-	-	Aktif
MI003	MITRA USAHA SEJATI /MUS	-	-	-	TUBAGUS ANGKE 6A BLOK C-7	JAKARTA	-	-	-	Aktif
JO002	JOHAN	-	-	-	JL. SIMOKERTO I/36	SURABAYA	-	-	-	Aktif
LA004	LANCAR	-	-	L	JL.KOPRAL USMAN NO.07	MALANG	-	0000-00-00	-	Aktif
MI002	MINOLTA	-	-	-	KARANG EMPAT B-65	SURABAYA	-	-	-	Aktif
MU003	MULYA MADYA	-	-	-	KOMPLEK SEMUT INDAH D-12A	SURABAYA	-	-	-	Aktif
LU004	LUKI	-	-	-	JL.	JAKARTA	-	-	-	Aktif
NE001	NEW SURYA	-	-	-	JL.BUNGURAN 23-25E	SURABAYA	-	-	-	Aktif
MA008	MANUNGGAL	-	-	-	JL.KEMBANG JEPUN 79	SURABAYA	-	-	-	Aktif
ME003	MEGAH JAYA	-	-	-	JL.KYAI TAMIN NO.105 H	MALANG	-	-	-	Aktif
KA003	KARYA KURNIA	-	-	-	KOMP.DHI BLOK  I NO.39	JAKARTA UTARA	-	-	-	Aktif
SU010	SURYA SEMESTA	-	-	-	PS.GOTONG ROYONG A9	PROBOLINGGO	-	-	-	Aktif
RA006	RANTAI MAS	-	-	-	PS.TURI LT.DASAR LD 15-21	SURABAYA	-	-	-	Aktif
DW001	DWI DJAYA	-	-	-	JL.PANGGUNG	SURABAYA	-	-	-	Aktif
PU004	PUTRA JAYA	-	-	-	JL.WONOSARI 36	SURABAYA	-	-	-	Aktif
MA007	MAKMUR JAYA	-	-	-	JL.GAJAH MADA 94	SIDOARJO	-	-	-	Aktif
MI001	MINI FOTO	-	-	-	JL.SIMOKATRUNGAN PASAR 15	SURABAYA	-	-	-	Aktif
SA006	SARIWANGI	-	-	-	KEMBANG JEPUN 136	SURABAYA	-	-	-	Aktif
SU009	SUBUR STATIONERY	-	-	-	JL.BARATAJAYA 18 NO.125	SURABAYA	-	-	-	Aktif
SU008	SUMBER HIDUP	-	-	L	JL.KOPRAL USMAN NO.5	MALANG	-	0000-00-00	-	Aktif
SC001	SCORPIO	-	-	-	JL.ZAMRUD 04	MALANG	-	-	-	Aktif
TI004	TIRTO WALUYO	-	-	-	JL. B.URIP KIDUL VI A/41	SURABAYA	-	-	-	Aktif
CO002	COUNTER	-	-	-	-	SURABAYA	-	-	-	Aktif
MA006	MASPION PT	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
JO001	JOKO TOLE	-	-	-	JL.JOKO TOLE 37	PAMEKASAN	-	-	-	Aktif
UT001	UTAMA JAYA	-	-	-	JL.KEMBANG JEPUN 164	SURABAYA	-	-	-	Aktif
BE001	BENTUL	-	-	-	JL.BENDUL MERISI 99	SURABAYA	-	-	-	Aktif
RE003	REJEKI	-	-	-	JL.TRUNOJOYO 14	SAMPANG	-	-	-	Aktif
RO002	PT.ROYAL STANDART	-	-	-	JL.MARGOMULYO IND.I/B-15	SURABAYA	-	-	-	Aktif
ST003	STANZA STATIONERY	-	-	-	KAMPUNG GUSTI TPI II.MI/7	JAKARTA - UTARA	-	-	-	Aktif
LI003	LIMAMAS SEJATI PT	-	-	-	JL.MYR KERTOADI S516/97	SURABAYA	-	-	-	Aktif
US001	USAHA JAYA	-	-	-	JL.KEMBANG JEPUN NO.125	SURABAYA	-	-	-	Aktif
HA004	HANZA	-	-	-	JL.INDUSTRI XXVI N0.1053	SEMARANG	-	-	-	Aktif
SE006	SEMESTA STATIONERY	-	-	-	KOMP SMG INDAH AIX/5-6	SEMARANG	-	-	-	Aktif
KO002	KOMPAK	-	-	-	JL. TENGKURUK PERMAI 88/B	PALEMBANG	-	-	-	Aktif
H-001	H-7	-	-	-	RUNGKUT MENANGGAL HRP.H-7	SURABAYA	-	-	-	Aktif
SA005	SANTOSO	-	-	-	JL.SERSAN HARUN LT.DSR 14	MALANG	-	-	-	Aktif
LA003	LARIS JAYA	-	-	-	JL. PRAMBON 133	KRIAN	-	-	-	Aktif
TI003	TIGA PUTRA UD	-	-	-	JL.KEMBANG JEPUN 160	SURABAYA	-	-	-	Aktif
PR001	PRIMA PENTAGUNA PT.	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
PA001	PANCA A.U	-	-	-	JL.PETAK BARU,PS.PAGI	BLOK C 46 JKT	-	-	-	Aktif
PU003	PUTRA GARUDA ELNUSA	-	-	-	MANGGA DUA PLAZA B-16	JAKARTA UTARA	-	-	-	Aktif
RU001	RUKUN	-	-	-	JL.PANGGUNG III/8A	SURABAYA	-	-	-	Aktif
SE005	SEJATI STATIONERY	-	-	-	JL.TIANG BENDERA V/24	JAKARTA KOTA	-	-	-	Aktif
SU007	SURYA INDO PRATAMA	-	-	-	JL. KARET 67	SURABAYA	-	-	-	Aktif
ST002	STAMINA STATIONERY	-	-	-	ROA MALAKA SELATAN 28/14	JAKARTA BARAT	-	-	-	Aktif
TI002	TIXIN SURYA ABADI	-	-	-	JL.PRAPANCA 50	SURABAYA	-	-	-	Aktif
SA004	SANWA WB	-	-	-	JL.TAMBAK SARI	SURABAYA	-	-	-	Aktif
SU006	SURYA INDAH	-	-	-	JL.MARGOMULYO 44 BLOK C11	-12, SURABAYA	-	-	-	Aktif
SI019	SINAR MAS	-	-	-	KAPUK MUARA DHI BLK.UU 16	JAKARTA	-	-	-	Aktif
SY001	SYAKIEB/FAHMI	-	-	-	JL.KALI SOSOK NO.12	SURABAYA	-	-	-	Aktif
SE004	SERITI	-	-	-	JL.INDUTRI XVIII/711	SEMARANG	-	-	-	Aktif
TR001	TRINOKO	-	-	-	JL.INDUSTRI 20 786/787	SEMARANG	-	-	-	Aktif
TA002	TAJALA PANCA JAYA	-	-	-	PRY.PERNIAGAAN LT.DSR C08	JAKARTA BARAT	-	-	-	Aktif
TU003	TUNGGAL JAYA	-	-	-	KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
TA001	TAJALI	-	-	-	TUBAGUS ANGKE BLOK EE 3	JAKARTA BARAT	-	-	-	Aktif
CA002	BUANA MAS JAYA	-	-	-	JL.SONGOYUDAN 43	SURABAYA	-	-	-	Aktif
BO003	BOOMAX	-	-	-	JL.JAKARTA NO.58B	SURABAYA	-	-	-	Aktif
AS002	ASABA PT	-	-	-	JL.IR.H.JUANDA NO.07	JAKARTA	-	-	-	Aktif
AA001	AA.SETIA	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
SI018	SINAR BALI	-	-	-	JL.KOL.ATMO 395A/433	PALEMBANG	-	-	-	Aktif
SI017	SINAR TERANG STATIONERY	-	-	-	JL. RAYA MULYOSARI,	SURABAYA	-	-	-	Aktif
OR001	ORIENTAL	-	-	-	JL.MAJAPAHIT 159	MOJOKERTO	-	-	-	Aktif
SU005	SUKSES	-	-	-	JL.RAYA A4	KRIAN	-	-	-	Aktif
RA005	RAHAYU	-	-	-	JL.MESJID 62	MOJOSARI	-	-	-	Aktif
MO001	MORODADI JAYA	-	-	-	PS.TURI BARU LT.IIIC/68	SURABAYA	-	-	-	Aktif
SI016	SINAR TERANG STATIONERY	-	-	-	JL. MULYOSARI,	SURABAYA	-	-	-	Aktif
TE004	TELAGA INDAH	-	-	-	JL.TENGKURUK PERMAI C/41	PALEMBANG	-	-	-	Aktif
YA001	YANSON TB	-	-	-	PS.ATOM LT.DASAR NO.1001	SURABAYA	-	-	-	Aktif
YU001	YUDY	-	-	-	JL. BABATAN PANTAI 2/4	SURABAYA	-	-	-	Aktif
VI002	VICKY CITRA JAYA	-	-	-	TM.PWI UTR CX-15/BLK	GIANT, SBY	-	-	-	Aktif
WI001	WIJAYA	-	-	-	JL.PETEMON BARAT 187A	SURABAYA	-	-	-	Aktif
VI001	VIVA TK	-	-	-	JL.MANUKAN LOR IF/10	SURABAYA	-	-	-	Aktif
VA001	VANILLA	-	-	-	JL. DARMO INDAH	SURABAYA	-	-	-	Aktif
TU002	TULUS HARAPAN	-	-	-	JL.KEMBANG JEPUN 127 G	SURABAYA	-	-	-	Aktif
TE003	TEGUH SURYA	-	-	-	JL.RANGKAH VII/18	SURABAYA	-	-	-	Aktif
TU001	TUNAS MEKAR	-	-	-	JL.	JKT	-	-	-	Aktif
TI001	TIGA JAYA	-	-	-	PS.BLAURAN	SURABAYA	-	-	-	Aktif
TO001	PIGURA JAYA	-	-	-	JL.KAPAS KRAMPUNG NO.39	SURABAYA	-	-	-	Aktif
TE002	TERANG ABADI	-	-	-	JL.KEMBANG JEPUN 85	SURABAYA	-	-	-	Aktif
SU004	SUMBER JAYA	-	-	-	JL.TIDAR 286	SURABAYA	-	-	-	Aktif
SE003	SEMESTA SELAKSA MUSIM	-	-	-	JL.IST MENTARI REGENCY	B4/21 SIDOARJO	-	-	-	Aktif
SU003	SUMBER BARU	-	-	-	JL.SIMO KWAGEAN 80 I	SURABAYA	-	-	-	Aktif
SU002	SUKMA ALAM JAYA	-	-	-	JL.RANGKAH VI/80	SURABAYA	-	-	-	Aktif
SI015	SINAR INDAH	-	-	-	JL.KESELAMATAN 6/B RT.011	/008,KRUKUT-JKT	-	-	-	Aktif
SI014	SINAR LANCAR	-	-	-	JL.WASPADA 96H	SURABAYA	-	-	-	Aktif
SA003	SANTOSO	-	-	-	JL.SIMORUKUN II/39	SURABAYA	-	-	-	Aktif
SI012	SINAR LOMBOK	-	-	-	JL. NGAGLIK NO. 1	SURABAYA	-	-	-	Aktif
TE001	TERANG ABADI	-	-	-	JL.KEMBANG JEPUN,	SURABAYA	-	-	-	Aktif
SI011	SINAR SURYA	-	-	-	JL.KEMBANG JEPUN 127-W	SURABAYA	-	-	-	Aktif
SU001	SUBUR	-	-	-	JL.PUCANG ANOM 11A	SURABAYA	-	-	-	Aktif
SE002	SETIA KAWAN	-	-	-	JL.KAPT.KYAI AYAS 149	LUMAJANG	-	-	-	Aktif
UD001	UD.99	-	-	-	JL.	JAKARTA	-	-	-	Aktif
SE001	SENTOSA BARU	-	-	-	LAWANG SEKETENG III/12	SURABAYA	-	-	-	Aktif
SI010	SINAR MAS	-	-	-	JL.KAPASAN 80	SURABAYA	-	-	-	Aktif
SI009	SINAR TERANG	-	-	-	BABATAN PANTAI BARAT I/49	SURABAYA	-	-	-	Aktif
SA002	SARANA PELITA	-	-	-	JL.SAMUDRA	SURABAYA	-	-	-	Aktif
SI008	SINAR ABADI	-	-	-	PS.TURI LT.I BLOK G-8	SURABAYA	-	-	-	Aktif
EN002	ENG HWA	-	-	-	JL.NGAGEL MULYO V/26	SURABAYA	-	-	-	Aktif
SI007	SISWA (1)	-	-	-	K.H AGUS  SALIM 149	MADIUN	-	-	-	Aktif
SA001	SAMI JOYO	-	-	L	JL.KYAI TAMIN 105-105B	MALANG	-	0000-00-00	-	Aktif
BU001	BUANA BARU	-	-	-	TERUSAN BANDENGAN UTR C/1	2A KOMP.SOKA	-	-	-	Aktif
SI006	SISWA	-	-	-	JL.MH.THAMRIN NO.17 A	TULUNG AGUMG	-	-	-	Aktif
SI005	SINAR KASIH	-	-	-	PS TURI BR LT 1/H-79	SURABAYA	-	-	-	Aktif
SI004	SINAR ABADI	-	-	-	JL.KEMBANG JEPUN 135/32B	SURABAYA	-	-	-	Aktif
ST001	STRADA	-	-	-	JL.DAAN MOGOT NO. 3/G-7	JAKARTA BARAT	-	-	-	Aktif
SI003	SIDODADI	-	-	-	JL.PETEMON KALI 77 G	SURABAYA	-	-	-	Aktif
SH001	SHINSHEN	-	-	-	PS.ATOM LT.I N0.1186	SURABAYA	-	-	-	Aktif
RE002	REJO AGUNG II	-	-	-	JL.ANGGREK NO.9	JOMBANG	-	-	-	Aktif
RA004	RACHMAD	-	-	-	JL.TAMBAKSARI 8P	SURABAYA	-	-	-	Aktif
RE001	REJEKI BARU	-	-	-	JL.JAGARAGA 30	SURABAYA	-	-	-	Aktif
RA003	RAHAYU	-	-	-	JL.KERTAJAYA 127 A	SURABAYA	-	-	-	Aktif
RA002	RAHAYU	-	-	-	PS.TURI LT.I BLOK E-15	SURABAYA	-	-	-	Aktif
RI001	RIA	-	-	-	JL.KALONGAN KIDUL I/1	SURABAYA	-	-	-	Aktif
RA001	RAHARJO	-	-	-	JL.KRANGGAN 54	SURABAYA	-	-	-	Aktif
RO001	ROBBY	-	-	-	JL.	SURABAYA	-	-	-	Aktif
QU001	QUEEN SUN	-	-	-	JL.PADI RAYA SELATAN 2	SEMARANG	-	-	-	Aktif
PI002	PING	-	-	-	ST.REJO TENGAH II/10 DD30	SURABAYA	-	-	-	Aktif
QO001	QOIS	-	-	-	SIMO GN.KRAMAT TIMUR NO.7	SURABAYA	-	-	-	Aktif
PI001	PING HWAT	-	-	-	JL.KUTISARI INDAH	SURABAYA	-	-	-	Aktif
OE001	OEN	-	-	-	JL.	SURABAYA	-	-	-	Aktif
NA005	NASIONAL	-	-	-	SEPANJANG TOWN HOUSE B-08	SEPANJANG	-	-	-	Aktif
NY001	NYOMAN	-	-	-	JL.GANDAPURA I/1,	DENPASAR-BALI	-	-	-	Aktif
NA004	NAGA SAKTI	-	-	-	JL.ADITYAWARMAN 60	SURABAYA	-	-	-	Aktif
NI001	NITA	-	-	-	JL.DARMOKALI 1F	SURABAYA	-	-	-	Aktif
MU002	MULTI REZEKI	-	-	-	RUKO VILA KAPUK MAS I,	BLOK A/8,JKT	-	-	-	Aktif
MA005	MANDIRI JAYA	-	-	-	JL.KB JEPUN 150B/26	SURABAYA	-	-	-	Aktif
MU001	MUTIARA	-	-	-	JL.BABATAN MUKTI E/44	SURABAYA	-	-	-	Aktif
MA004	MANYAR JAYA	-	-	-	JL.MANYAR 2-4	SURABAYA	-	-	-	Aktif
ME002	MEGAH SUKSES STATIONERY	-	-	-	JL.	JAKARTA	-	-	-	Aktif
MA003	MAKMUR	-	-	-	JL.KALIMALANG 11F	SURABAYA	-	-	-	Aktif
ME001	MELATI	-	-	-	JL.SONGOYUDAN 34	SURABAYA	-	-	-	Aktif
MA002	MARCO MARIO SOUVENIR	-	-	-	JL.PLASA SEGI 8 SCTV	SURABAYA	-	-	-	Aktif
SI002	SINAR JAYA   UD	-	-	-	JL.KEMBANG JEPUN 150B 26	SURABAYA	-	-	-	Aktif
LU003	LUCKMAN STATIONERY	-	-	-	JL.KEMBANG JEPUN	SURABAYA	-	-	-	Aktif
LU002	LUSY	-	-	-	SIDOTOPO WETAN BARU 06	SURABAYA	-	-	-	Aktif
LA002	LARIS	-	-	-	JL.WONOKUSUMO 66	SURABAYA	-	-	-	Aktif
LA001	LAS SUGIARTO	-	-	-	S.ALIMUDIN GG PERJUANGAN	I/115 SAMARINDA	-	-	-	Aktif
LU001	LUMAYAN	-	-	-	PS.TB.REJO LT.DSR A-2A	SURABAYA	-	-	-	Aktif
LI002	LION	-	-	-	JL.KEMBANG JEPUN 164	SURABAYA	-	-	-	Aktif
LI001	LIE KWANG	-	-	-	JL.SAWAHAN TEMPLEK	SURABAYA	-	-	-	Aktif
KW001	KWAN TB	-	-	-	JL.PENELEH	SURABAYA	-	-	-	Aktif
GE001	GESSY & YOKO	-	-	-	PULO WONOKROMO WETAN I/30	SURABAYA	-	-	-	Aktif
GU002	GUNAWAN(TH)	-	-	-	JL.PASAR BESAR WETAN 10A	SURABAYA	-	-	-	Aktif
GA004	GAYA REMAJA	-	-	-	JL.GEMBONG 2-16 BLOK B-5	SURABAYA	-	-	-	Aktif
FO002	FOTO COPY MINOLTA	-	-	-	JL.KARANG EMPAT BESAR 65	SURABAYA	-	-	-	Aktif
FE001	FEBRY	-	-	-	JL.WONOREJO III/76	SURABAYA	-	-	-	Aktif
EN001	ENAM-ENAM	-	-	-	JL.WONOREJO IV/66	SURABAYA	-	-	-	Aktif
81001	81	-	-	-	JL. RAYA 336,	GENTENG	-	-	-	Aktif
DJ001	DJAYA SENTOSA	-	-	-	PRADAH PERMAI I/11	SURABAYA	-	-	-	Aktif
BI007	BINA MULIA	-	-	-	JL.JAGALAN 70	SURABAYA	-	-	-	Aktif
BO002	BOROBUDUR	-	-	-	PANJANG JIWO PERMAI I/3	SURABAYA	-	-	-	Aktif
BA002	BAROKAH LUBIS	-	-	-	JL.SIDOTOPO WETAN V/12	SURABAYA	-	-	-	Aktif
AL003	AL AMIN	-	-	-	PS.PUCANG STAND AA 35-36	SURABAYA	-	-	-	Aktif
AN004	ANDA	-	-	-	JL.PUCANG ANOM 18	SURABAYA	-	-	-	Aktif
AG001	AGUS STATIONERY	-	-	-	JL.KREMBANGAN BAKTI N0.28	SURABAYA	-	-	-	Aktif
AP003	APOLLO	-	-	-	JL. STAND SAHABAT 16	SURABAYA	-	-	-	Aktif
MA001	MARANATHA	-	-	-	PS.TURI LT.I BLOK G-27/28	SURABAYA	-	-	-	Aktif
KO001	KOTA RAME	-	-	-	JL.KEMBANG JEPUN 149	SURABAYA	-	-	-	Aktif
KI002	KIM HWA/BUNGA MAS	-	-	-	JL.JAGALAN 138	SURABAYA	-	-	-	Aktif
KI001	KILAT BARU	-	-	-	JL.PANDEGILING 231	SURABAYA	-	-	-	Aktif
KA002	KAWISAN	-	-	-	JL.KEMBANG JEPUN 127-H	SURABAYA	-	-	-	Aktif
KA001	KAMI	-	-	-	JL.JATI SRONO NO.14	SURABAYA	-	-	-	Aktif
KE001	KENSHINDO CHEMIE	-	-	-	JL.TENGGILIS MULYA 95	SURABAYA	-	-	-	Aktif
JA005	JAWA	-	-	-	JL.KEDUNGDORO 251	SURABAYA	-	-	-	Aktif
JA004	JAYA MAKMUR	-	-	-	SULTAN ISKANDAR MUDA 23	SURABAYA	-	-	-	Aktif
JA003	JAYA RAYA	-	-	-	JL.KEMBANG JEPUN 147A	SURABAYA	-	-	-	Aktif
JA002	JAYA AROFAH	-	-	-	JL.SIMOREJOSARI A-22M	SURABAYA	-	-	-	Aktif
JA001	JAYA	-	-	-	PS.ATOM LT.DSR TH.I 1137	SURABAYA	-	-	-	Aktif
IS001	ISTANA 2	-	-	-	JL. DR WAHIDIN SH BLOK E3	LAMONGAN	-	-	-	Aktif
IA001	IAS SUGIARTO	-	-	-	JL. DAMANHURI RT.36/43	SAMARINDA	-	-	-	Aktif
IM001	IMANUEL	-	-	-	JL.KAPAS GADING MADYA V/1	SURABAYA	-	-	-	Aktif
HI001	HIDAYAH	-	-	-	JL.KEDUNG WUNGU TIMUR 123	SURABAYA	-	-	-	Aktif
HA003	HANURA	-	-	-	JL.BRATANG GEDE 141	SURABAYA	-	-	-	Aktif
HA002	HANDAYANI	-	-	-	JL.JAGIR WONOKROMO W.22	SURABAYA	-	-	-	Aktif
HE004	HERMAN	-	-	-	JL.TAMBAK ARUM VII/16	SURABAYA	-	-	-	Aktif
HE003	HERMAWAN	-	-	-	JL.TAMBAKSARI 8D	SURABAYA	-	-	-	Aktif
HE002	HERO	-	-	-	JL.	MANADO	-	-	-	Aktif
HA001	HARAPAN JAYA	-	-	-	PETA LINGKAR SELATAN 101	BANDUNG	-	-	-	Aktif
HE001	HENDRICK/SUMBER REJEKI A	-	-	-	JL. VETERAN NO. 2 RT.23	BANJARMASIN	-	-	-	Aktif
SI001	SINAR GEMILANG	-	-	-	JL.CANDI MENDUT BARAT B/1	MALANG	-	-	-	Aktif
GA003	GANGSAR	-	-	-	JL.DEMAK 185	SURABAYA	-	-	-	Aktif
GA002	GATSBY	-	-	-	JL.GENTENG BESAR NO.80	SURABAYA	-	-	-	Aktif
GU001	GUNAWAN UD	-	-	-	JL.HP.KUSUMA 38	SUMENEP	-	-	-	Aktif
GA001	SAMUDRA ANGKASA JY	-	-	-	JL.MULYOSARI 170	SURABAYA	-	-	-	Aktif
FA004	FAJAR MINI MARKET	-	-	-	JL.AHMAD YANI 246	SURABAYA	-	-	-	Aktif
FO001	FOTO COPY	-	-	-	JL.HANG TUAH NO.06	SURABAYA	-	-	-	Aktif
FA003	FABERINDO	-	-	-	JL.	SURABAYA	-	-	-	Aktif
FA002	FAJAR MULIA	-	-	-	JL.PACUAN KUDA 25	SURABAYA	-	-	-	Aktif
FA001	FAJAR	-	-	-	JL.GIRILAYA 1C	SURABAYA	-	-	-	Aktif
EL001	EL MALIK	-	-	-	JL.JEND.SUDIRMAN 37/55	SUMENEP	-	-	-	Aktif
DE001	DELAPAN ENAM	-	-	-	JL.SIDODADI 86	SURABAYA	-	-	-	Aktif
DU004	DUNIA TISSUE	-	-	-	JL.	SURABAYA	-	-	-	Aktif
DU003	DUTA PLASTIK	-	-	-	DUTA HARAPAN BLOK N-43	JAKARTA UTARA	-	-	-	Aktif
DU002	DUA EMPAT	-	-	-	JL.PANGGUNG	SURABAYA	-	-	-	Aktif
DA001	DAYA FANCY	-	-	-	JL.	SURABAYA	-	-	-	Aktif
DU001	DUA EMPAT	-	-	L	JL.TELUK PELABUHANRATU 30	MALANG	-	0000-00-00	-	Aktif
CA001	CAHAYA STATIONERY	-	-	-	JL.INDUSTRI XXIV/982(LIK)	SEMARANG	-	-	-	Aktif
BI006	BIMA STATIONARY	-	-	-	JL.	SURABAYA	-	-	-	Aktif
BI005	BINTANG SAUDARA	-	-	-	KOMP.SOKA E-29/30	JAKARTA UTARA	-	-	-	Aktif
BM004	BMW MEDAN	-	-	-	HOS.COKROAMINOTO 07/59 I	MEDAN	-	-	-	Aktif
BI004	BINA MULIA	-	-	-	JL.KEBALEN TIMUR 57	SURABAYA	-	-	-	Aktif
BA001	BAMBANG	-	-	-	JL.MASPATI VI/49	SURABAYA	-	-	-	Aktif
BI003	BING	-	-	-	JL.MAWAR C-19/6 PERUM BE-	DALI IND,LAWANG	-	-	-	Aktif
BI002	BINTANG KASIH	-	-	-	JL.SLAGAH NO.14	PASURUAN	-	-	-	Aktif
BI001	BINTANG MULIA	-	-	-	JL.KH MOH.KHOLIL 65	BANGKALAN	-	-	-	Aktif
A 002	A SIUNG	-	-	-	JL.	JAKARTA	-	-	-	Aktif
AN003	ANWAR	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AB002	ABADI PD	-	-	-	JL.H.KURDI NO.184	BANDUNG	-	-	-	Aktif
AN002	ANATA RAYA PT	-	-	-	PO.BOX 245	SOLO	-	-	-	Aktif
AD002	ADI PERDANA STATIONERY	-	-	-	JL.KARTINI 64	SIDOARJO	-	-	-	Aktif
AP002	APOLLO	-	-	-	JL.KEMBANG JEPUN 144/26	SURABAYA	-	-	-	Aktif
AP001	APOLLO	-	-	-	JL.TRUNOJOYO 15-17	PAMEKASAN	-	-	-	Aktif
AB001	ABC	-	-	-	JL.BENDUL MERISI 08	SURABAYA	-	-	-	Aktif
AL002	ALPHINDO STATIONERY	-	-	-	TAMAN COSMOS BLOK O/8,	JAKARTA-BARAT	-	-	-	Aktif
AS001	ASEN	-	-	-	JL.KEDUNG KLINTER I/43	SURABAYA	-	-	-	Aktif
AD001	ADI	-	-	-	JL.	SURABAYA	-	-	-	Aktif
AL001	ALUN MEGAH PERKASA	-	-	-	JL.	SURABAYA	-	-	-	Aktif
A 001	A GUAN	-	-	-	JL.	JKT	-	-	-	Aktif
AN001	ANUGRAH TERANG KARUNIA	-	-	-	JL.SIMO SIDOMULYO IV/8A	SURABAYA	-	-	-	Aktif
CO001	COSINUS ALFA	-	-	-	PS.TURI BARU LT.1G-15	SURABAYA	-	-	-	Aktif
AU001	AUK	-	-	-	DARMO HILL BLOK O NO.38	SURABAYA	-	-	-	Aktif
PU002	PUTRA SATRIA	-	-	-	JL.MANUKAN LOR 3K/7	SURABAYA	-	-	-	Aktif
PU001	PUTRO AGUNG	-	-	-	JL.KALIMALANG 11E	SURABAYA	-	-	-	Aktif
BO001	BONA	-	-	-	JL.	JAKARTA	-	-	-	Aktif
BM003	BMW JAKARTA	-	-	-	JL.MUARA KARANG F-9 SEL90	JAKARTA	-	-	-	Aktif
BM002	BMW SEMARANG	-	-	-	JL.INDUSTRI IV NO.120	SEMARANG	-	-	-	Aktif
BM001	BMW SURABAYA	-	-	-	KOM.RUKO MANGGA DUA	SURABAYA	-	-	-	Aktif
NA002	NATALIN / BLAURAN	-	-	-	PS.BLAURAN LT.1A 90-95	SURABAYA	-	-	-	Aktif
NA001	NATALIN / MANGGA DUA	-	-	-	RUKO MANGGA DUA A10/17	SURABAYA	-	-	-	Aktif
";?>